### ISSUE TITLE
Desktop Support

### ISSUE THREAD

**Issue by shinaka** [RafaelBarbosatec/bonfire#102]
It looks like Bonfire doesn't support desktop platforms currently (at least Windows?)
I managed to get darkness dungeon to build, but it spams renderbox size errors. Was just wondering if this is a known issue before I start digging in further?

**Comment by RafaelBarbosatec** [comment]
Hi @shinaka !
Bonfire has desktop support using an RC version.
The dark dungeon project has not yet had time to upgrade to the latest version of Bonfire.
Try test with example of the package.
