### ISSUE TITLE
I want to achieve X-direction flip animation

### ISSUE THREAD

**Issue by ym6745476** [RafaelBarbosatec/bonfire#103]
I want to achieve X-direction flip animation, this writing seems not to work, thank you for your guidance
`
void render(Canvas canvas) {

    if (position == null) return;

    //renderFlipX
    if (renderFlipX) {
      print("renderFlipX:" + position!.width.toString() + "," + position!.height.toString());
      canvas.translate(position!.width / 2, position!.height / 2);
      canvas.scale(-1.0,1.0);
      canvas.translate(-position!.width / 2, -position!.height / 2);
    }

    if (_fastAnimation != null) {
      _fastAnimation?.render(canvas);
    } else {
      current?.getSprite().renderFromVector2Rect(canvas, position!);
    }
  }`

**Comment by RafaelBarbosatec** [comment]
Hi @zhaoqp2010 !
This is some kind of effect that you are trying to have on your game. Or are you trying not to use a SpriteAnimation for each direction?
