### ISSUE TITLE
flame-1.0.0-releasecandidate.11 update textconfig.dart to text.dart

### ISSUE THREAD

**Issue by tsehonkit** [RafaelBarbosatec/bonfire#109]
Hi,

Bonfire is amazing. I am studying how to use it. As flame update to releasecandidate 11, the textconfig.dart and the corresponding class elements are modified and becomes text.dart. No more TextConfig exists.
It broke into TextRenderer, TextPaintConfig, BaseTextConfig, TextPaint etc.

**Comment by AlexV525** [comment]
Downgrade `flame` to `1.0.0-rc9` seems to be a temporary workaround.

**Comment by RafaelBarbosatec** [comment]
Downgrade in version 1.0.2.
