### ISSUE TITLE
The size of the tile of the tileset may be bigger than the size of the tile of the map.

### ISSUE THREAD

**Issue by kuyum** [RafaelBarbosatec/bonfire#112]
The size of the tile of the tileset may be bigger than the size of the tile of the map, such as tall trees or big houses. That is, a big image over rendering on a small tile, covering its neighbors rather than shrinking it. For now it have to be divided into multi tiles, and it is inconvenient to draw collision area.

**Comment by KyleKun** [comment]
Hey @kuyum ,
Could you attach some screenshots as examples?

**Comment by kuyum** [comment]
yep
**First use case**
[TestMapScreenShot](https://github.com/kuyum/pubImages/blob/main/map_screen_shot_001.png)
The tile size of the map is 64x64. The first layer is using a earth tileset which tile size is 64x64. Their tile size is equal to each other.
The second layer is using a houses tileset which tile size is 256x203, its tile size is more bigger than the tile size of the map. It will cover several tiles of the map.

**Second use case**
[TestTile](https://github.com/kuyum/pubImages/blob/main/stone_W.png)
[TestMapScreenShot2](https://github.com/kuyum/pubImages/blob/main/map_screen_shot_002.png)
The tile size of the tileset is not equal to the tile size of the map.
The tile size of the map is 180x256, but the tile size of the tileset is 512x256.
The tile image will cover part of its previous tile or even more.

**Comment by RafaelBarbosatec** [comment]
I guess It’s not problem about Bonfire. Please look for some way to help you with doubts about map maintenance with Tiled.
