### ISSUE TITLE
After I upgrade to bonfire version 1.0.3, it cant play upRight animation.

### ISSUE THREAD

**Issue by kuyum** [RafaelBarbosatec/bonfire#113]
After I upgrade to bonfire version 1.0.3, it cant play upRight animation. 
When I drag the joystick_nob to upRight direction, 
it call three move methods one by one, first moveUpRight, then moveRight, finally moveUp.
And finally it play the up animation. 
In other words, the upRight animation has not been played, but the up animation is playing.

**Comment by RafaelBarbosatec** [comment]
Hi @kuyum. Thanks for issue!
I'm analyzing

**Comment by RafaelBarbosatec** [comment]
Fix in 1.1.1 version

**Comment by kuyum** [comment]
It works now, thank you!
