### ISSUE TITLE
JoystickMoveToPosition not working as expected

### ISSUE THREAD

**Issue by KyleKun** [RafaelBarbosatec/bonfire#115]
Hello,

I'm trying to use JoystickMoveToPosition on my map built with tiled where my objects have polygon collision, but the a_star algorithm seems to not detect them, resulting in locking the player as shown in the video:

https://user-images.githubusercontent.com/36611739/120941106-42827600-c6f7-11eb-8049-e488e7fcb6cf.mp4

**Comment by RafaelBarbosatec** [comment]
Hi @KyleKun !
Those elements that contain collision were added as Decoration or by Tiled

**Comment by KyleKun** [comment]
By Tiled only

**Comment by RafaelBarbosatec** [comment]
humm. Ok
I will try to reproduce here. can you send a print with the showCollisionArea property equal to true?

**Comment by KyleKun** [comment]
![20210608_205001.jpg](https://user-images.githubusercontent.com/36611739/121271934-20c1f400-c89b-11eb-86b7-7d0cb409d29f.jpg)

It's very difficult to see because of the color but the collision is there, player collides with normal joystick

**Comment by KyleKun** [comment]
I've tested a little bit more and it seems that collisions are overlapping and this is the cause of "locking" the player, player's collision enters the object's collision

**Comment by RafaelBarbosatec** [comment]
Understand. I will try to simulate a scenario similar to yours. Because it wasn't to trace a route that passes through the objectives that have collision.
In the example of the package it works perfectly.
I'll investigate further.

**Comment by RafaelBarbosatec** [comment]
Could you send me a print with constructionMode: true ?
Just to get a sense of the tileSize of the map.
Because if there is something collision on the tile. it already discards that option as a path.
I've already noticed an adjustment that needs to be done.

**Comment by KyleKun** [comment]
Sure, tileSize is 16x16 and "double tileSize" is 20.0 on main.dart

Map is small: ![Screenshot_20210609-161805_Gallery.png](https://user-images.githubusercontent.com/36611739/121415602-4d7b1780-c93e-11eb-8242-49710162e0d5.png)

**Comment by RafaelBarbosatec** [comment]
I've already identified the problem. I'm thinking here of a way to solve this. Hahaha
I set up a matrix to send the algorithm to calculate the path. But in this matrix I'm noticing that a very large collision object occupies more than one cell in the matrix and I wasn't considering that.

**Comment by RafaelBarbosatec** [comment]
Hi @KyleKun 
I guess what resolve this problem.
Fiz available in 1.1.2 version.
I also updated the documentation with more information about this functionality.
https://bonfire-engine.github.io/#/path_finding

I hope it’s works good 😊

**Comment by KyleKun** [comment]
Will test it asap, thanks very much!

**Comment by KyleKun** [comment]
The scenario with the table and chairs is fixed, but it still happens in some places:
https://user-images.githubusercontent.com/36611739/121782389-a5549100-cb7f-11eb-8c09-d22e950f1a58.mp4

https://user-images.githubusercontent.com/36611739/121782398-aab1db80-cb7f-11eb-8662-f10310f0c0eb.mp4

**Comment by RafaelBarbosatec** [comment]
Try uses 1.1.3 version.

**Comment by KyleKun** [comment]
Hi @RafaelBarbosatec ,
It still happens in some places, and now the player movement is a little "shaky", check the video:

https://user-images.githubusercontent.com/36611739/121969779-607d5580-cd4b-11eb-896f-de2b60427a0c.mp4

**Comment by RafaelBarbosatec** [comment]
Good suggestions. I will work on it.
In this specific case it is because it currently checks for visible collisions on the screen. and on this particular route, he had to turn around and pass a chair that wasn't on the screen.
I can fix it too. increasing the size of the space for route analysis.

**Comment by RafaelBarbosatec** [comment]
You can check theses spaces that is considered collision adding:
```dart
        setupMoveToPositionAlongThePath(
            showBarriersCalculated: true, 
        )
```
in the player constructor.

**Comment by RafaelBarbosatec** [comment]
Hi @KyleKun !
Retest with the latest version please

**Comment by KyleKun** [comment]
It works like a charm!
I'll be closing this issue, thank you once again xD
