### ISSUE TITLE
Type mismatch in tile_set.dart

### ISSUE THREAD

**Issue by hanskokx** [RafaelBarbosatec/bonfire#120]
`tile_set.dart` line 55 `version = json['version'];` throws an exception with `json` exported from Tiled 1.6.  In the exported file, the version is quoted, and therefore a string.

**Comment by KyleKun** [comment]
Hey @hanskokx , 

If I am not mistaken, Bonfire supports Tiled version 1.3.5, try using this one, I've had no issues exporting maps in this version.

**Comment by hanskokx** [comment]
Well, that seems silly.  The problem could be easily solved by changing
`version = json['version'];` to `version = json['version'] is double ? json['version'] : double.parse(json['version']);`

**Comment by RafaelBarbosatec** [comment]
Try use 1.1.5 version.

**Comment by hanskokx** [comment]
Simply removing the quotes makes the file compatible, as far as I can tell.
