### ISSUE TITLE
Compile error after using bonfire into a newly created project.

### ISSUE THREAD

**Issue by ahde46** [RafaelBarbosatec/bonfire#127]
Hi,

Hope you are doing well and thank you for creating this awesome plugin.

I am able to compile and run the example project in this repo. And I can add bonfire into my pubspec.yaml. However, I can't compile the app after I trying to use the package in a dart file in a new project.

Please help me, and let me know if you need more information for the issue.

Thanks!
 
My Flutter version: 
<img width="592" alt="Screenshot 2021-07-12 at 5 40 18 PM" src="https://user-images.githubusercontent.com/49631831/125267407-5a25cd80-e339-11eb-9e9d-c6b3d9020af5.png">

Errors:
<img width="1117" alt="Screenshot 2021-07-12 at 5 12 24 PM" src="https://user-images.githubusercontent.com/49631831/125267442-6578f900-e339-11eb-860e-09bb268a68e4.png">

**Comment by RafaelBarbosatec** [comment]
Hi @ahde46 !
You did adds `flame` in you pubspec.yaml?
To use Bonfire not need import `flame` in your pubspec.yaml.
Bonfire is not compatible with version `releasecandidate.13` of `flame`.

**Comment by KyleKun** [comment]
Hi!

I'm getting the same error after updating bonfire to 1.3.0.
I don't have `flame` on pubspec.yaml.

**Comment by RafaelBarbosatec** [comment]
Hi @KyleKun .
For now use the 0.1.0-rc5 version of flame_audio. This one works really well.
This new version of Flame had some changes that won't be so trivial to make.

**Comment by ahde46** [comment]
Hi @RafaelBarbosatec ,

Thanks for pointing out the issue!

I don't have flame in my pubspec.yaml. However, I checked my pubspec.lock, bonfire: ^1.3.0 will pull the releasecandidate.13 of flame for my cases.

I am able to solve this issue by importing the version releasecandidate.12 of flame into my pubspec.yaml.

I will close this issue for now, thanks again!
