### ISSUE TITLE
Can't show a dialog on TalkDialog finish method

### ISSUE THREAD

**Issue by KyleKun** [RafaelBarbosatec/bonfire#129]
Hey!

I'm trying to show a dialog on the finish method of TalkDialog after making contact with an object, but this causes the last Say to keep on screen forever and the dialog is not shown.

```
@override
  void onContact(GameComponent component) {
    if (component is Player && !alreadyTalked) {
      alreadyTalked = true;
      TalkDialog.show(
        gameRef.context,
        [
          Say('a'),
          Say('b'),
          Say('c'),
        ],
        finish: () => _showMyDialog(),
      );
    }
  }

  void _showMyDialog() {
    print('working'); // This is sucessfully printed on the console, so the method is being called without problems
    showDialog(
      context: gameRef.context,
      builder: (context) => AlertDialog(
        title: Text(
          "This is a dialog",
        ),
      ),
    );
}
```
There are no errors on the console.

I can get it to work if I set a variable in this finish method from the Player class, which is listened on update(), but I don't know if this is the best approach since I will have lots of scenarios like this and would have to listen to many things on the Player update().

Any ideas what to do in this scenario? Thanks!

**Comment by RafaelBarbosatec** [comment]
Hi @KyleKun !
Try adds a little time before show next Dialog like:
```dart
finish: () async {
  await Future.delayed(Duration(milliseconds: 100));
  _showMyDialog()
},
```

**Comment by KyleKun** [comment]
Works like a charm!
Thanks once again 😄
