### ISSUE TITLE
Unneccessary logs if index passed to _getDataTile is more than 1025

### ISSUE THREAD

**Issue by akashsharma95** [RafaelBarbosatec/bonfire#133]
version: `1.3.4`

This causes huge number of logs while loading tilemap. 

https://github.com/RafaelBarbosatec/bonfire/blob/master/lib/tiled/tiled_world_map.dart#L281

**Comment by RafaelBarbosatec** [comment]
Thanks for open this issue. Fixed in 1.3.5 version.
