### ISSUE TITLE
[Proposal] Make Bonfire Website Open-Source to Allow Contributions

### ISSUE THREAD

**Issue by KyleKun** [RafaelBarbosatec/bonfire#146]
Hi!

I would like to help fixing typos and improving the docs at: https://bonfire-engine.github.io/
If it is possible, just let me know!

**Comment by RafaelBarbosatec** [comment]
Sure!
Its is amazing!
Here you go: https://github.com/bonfire-engine/bonfire-engine.github.io

**Comment by KyleKun** [comment]
Thanks! Closing this issue 😁
