### ISSUE TITLE
Tiled Map sometimes does not render some tiles

### ISSUE THREAD

**Issue by KyleKun** [RafaelBarbosatec/bonfire#150]
Hi @RafaelBarbosatec !

I'm testing some things and found this problem (reproduced on Web & Windows in debug and release modes, the issue still happens, did not test on Android but it is very likely that it happens as well), I'm using the latest version and this doesn't show any error logs:

https://user-images.githubusercontent.com/36611739/128794215-da189919-c0f6-4d79-8a81-60b95c297f94.mp4

OBS: Delay is from my screenrecorder, there is no delay in the game, just the black squares issue.
The map is 39x36 (tile size is 16 pixels), only common tiles without collisions.

**Comment by RafaelBarbosatec** [comment]
After refactoring to dynamically create Tiles. I've been watching these lag. I'm trying to work this out.

**Comment by RafaelBarbosatec** [comment]
Hi @KyleKun !
Try use the version 1.4.8

**Comment by KyleKun** [comment]
Hi @RafaelBarbosatec ,
Tested and it is working! Thank you!
