### ISSUE TITLE
TiledWorldMap doesn't render transformed tiles

### ISSUE THREAD

**Issue by SecareLupus** [RafaelBarbosatec/bonfire#182]
### Bonfire silently fails to render any TiledWorldMap tiles which have been rotated or reflected.

You can see in the two screenshots below comparing Tiled's preview, and Bonfire's rendering. There is an inside corner of the top-left room missing. These tiles were rotated, as the tileset only included 2 inner corners. Additionally, the center-top hallway connecting the top-left and top-right rooms is not rendered at all. This hallway was composed of reflected tiles, as the tileset does not include an east-facing doorway, and once I had reflected tiles to build the left half of the hallway, it was easier to just reflect the stamp again to complete the hallway.

Below the screenshots, I have included the data structure from worldmap.json which contains the map itself. Without knowing precisely how it's generated, I'd assume the tiny numbers are tile indexes, and the longer numbers are the tiles which have been transformed, but Bonfire seems to be ignoring them entirely.

Tiled Map Editor Preview:
![Expected](https://user-images.githubusercontent.com/3342468/136489992-3324cd19-efe2-4bdc-92c1-e73c39962750.png)

Bonfire-rendered map:
![Actual](https://user-images.githubusercontent.com/3342468/136489827-406a4005-ee90-4f50-9d86-178b6e9c3f06.png)

Relevant Map JSON entry:
`"data":[3, 4, 5, 6, 7, 8, 4, 5, 6, 7, 8, 9, 0, 0, 0, 0, 0, 0, 3, 4, 5, 6, 7, 8, 9, 28, 48, 48, 30, 13, 23, 16, 14, 16, 31, 29, 41, 536870954, 536870963, 2684354611, 2684354611, 2684354611, 2684354602, 12, 17, 25, 29, 38, 29, 41, 37, 40, 25, 17, 29, 29, 14, 48, 26, 49, 40, 18, 536870955, 536870928, 2684354607, 2684354599, 2684354576, 2684354603, 2147483666, 25, 25, 29, 26, 17, 50, 46, 38, 24, 26, 40, 22, 30, 14, 53, 17, 40, 27, 536870956, 536870952, 2684354607, 2684354576, 2684354600, 2684354604, 2147483675, 53, 22, 49, 39, 31, 41, 55, 56, 57, 58, 57, 1610612748, 1610612757, 26, 30, 39, 52, 50, 536870957, 536870966, 2684354614, 2684354614, 2684354614, 2684354605, 28, 38, 47, 38, 38, 40, 50, 0, 0, 0, 0, 0, 0, 37, 52, 22, 16, 16, 41, 0, 0, 0, 0, 0, 0, 37, 16, 23, 53, 49, 39, 41, 0, 0, 0, 0, 0, 0, 46, 39, 38, 15, 24, 50, 0, 0, 0, 0, 0, 0, 28, 52, 30, 52, 14, 22, 50, 0, 0, 0, 0, 0, 0, 55, 56, 57, 58, 62, 63, 0, 0, 0, 0, 0, 0, 37, 31, 22, 47, 14, 13, 41, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 46, 31, 53, 25, 47, 31, 50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 28, 24, 17, 14, 15, 38, 54, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 37, 30, 25, 48, 16, 38, 54, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 46, 25, 53, 13, 39, 26, 54, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 55, 56, 57, 34, 35, 62, 63, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 42, 43, 44, 45, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 51, 39, 16, 54, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 51, 16, 40, 54, 0, 3, 4, 5, 6, 7, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7, 5, 6, 7, 45, 0, 51, 39, 16, 54, 0, 12, 48, 31, 17, 26, 17, 26, 48, 31, 17, 26, 48, 31, 17, 26, 22, 38, 49, 54, 0, 51, 47, 47, 54, 0, 28, 17, 22, 52, 26, 52, 26, 17, 22, 52, 26, 17, 22, 52, 26, 25, 38, 48, 54, 0, 51, 49, 22, 54, 0, 37, 14, 38, 40, 13, 40, 13, 14, 38, 40, 13, 14, 38, 40, 13, 26, 14, 15, 54, 0, 51, 17, 25, 54, 0, 55, 56, 57, 56, 57, 56, 57, 56, 57, 56, 57, 56, 57, 56, 57, 58, 34, 35, 63, 0, 51, 48, 47, 54, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 42, 43, 44, 7, 8, 21, 31, 15, 54, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 51, 13, 38, 14, 13, 13, 25, 25, 54, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 51, 13, 49, 40, 31, 53, 29, 22, 54, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 60, 56, 57, 58, 58, 58, 58, 62, 63, 0],`

**Comment by RafaelBarbosatec** [comment]
Hi @SecareLupus !
Try use version 1.11.1
