### ISSUE TITLE
Errors in documentation

### ISSUE THREAD

**Issue by tomwyr** [RafaelBarbosatec/bonfire#190]
Dead links:
 - https://github.com/RafaelBarbosatec/bonfire/blob/master/example/lib/enemy/goblin.dart
 - https://bonfire-engine.github.io/#/Objects
 
Missing translation:
 - https://bonfire-engine.github.io/#/objects?id=flyingattackobject

Typo (_by defauld_):
- https://bonfire-engine.github.io/#/path_finding

**Comment by RafaelBarbosatec** [comment]
Thanks for notifications!
All these points have been resolved!
