### ISSUE TITLE
TiledMap rendering wrong tiles

### ISSUE THREAD

**Issue by KyleKun** [RafaelBarbosatec/bonfire#200]
Regarding the issue discussed on discord, I made a reproducible example: https://github.com/KyleKun/bonfire_1_99_tiled_bug

Tiled map properties: 32 columns x 18 rows and tile size is 60x60 px

Actual:
![issue](https://user-images.githubusercontent.com/36611739/141692739-8cd99052-8d01-4296-9333-d5d93468e608.PNG)

Expected:
![bonfire-bug](https://user-images.githubusercontent.com/36611739/141692686-89537462-1916-43d5-8a2a-861c1810c661.png)

**Comment by RafaelBarbosatec** [comment]
Thanks for this report!
Fixed in version 1.9.10!
