### ISSUE TITLE
Tiled: using polygon from object layer to create transparent collision object

### ISSUE THREAD

**Issue by tchex** [RafaelBarbosatec/bonfire#210]
Hello and thank you for your great work. It is really nice and powerful to work with bonfire.
Is it possible to create a polygon in Tiled (object layer) and to define it as a collision object with bonfire ?
For example, on a beach, create a polygone around the sea, to force player to stay on the beach.
Thanks !

**Comment by RafaelBarbosatec** [comment]
Hi @tchex !
Thanks so much!
Create an object with collision in Tiled is not possible in the moment. You can add collision by Tiled in your tiles in your tileset. Currently, when I want to make a collision of this type, I place a collision on a transparent tile and add it to the options where I want it to have a collision.

**Comment by tchex** [comment]
Hi @RafaelBarbosatec,
Thank you, I will use the transparent tiles.
I look forward to see your implementation as it will allow to create barriers, paths.. very easily and activate / unactivate these objects programatically. (forbidden area until quest finished..)

**Comment by RafaelBarbosatec** [comment]
Hi @tchex !
This features is available in version `1.12.2`.
Only set in type object to `collision` in your ObjectLayer of the Tiled.
The Bonfire will add a `CollisionGameComponent`.

**Comment by tchex** [comment]
Hi @RafaelBarbosatec!
That's great! Not tested yet, but thanks for your work. I guess Bonfire will have more and more success as Flame is now part of flutter official.

**Comment by tchex** [comment]
Hi @RafaelBarbosatec,
Thanks again: I tried and it works!
But not perfectly. Object is not placed at the right place. And sometimes disappears.. It seems to happen when a corner of the shape is out of the screen but not the object. (my object is way larger than the screen). I will try to do more tests to give you some better feedback.

**Comment by RafaelBarbosatec** [comment]
Right, I'll test more this case to find this problem.
Thanks for reporting. 😊

**Comment by RafaelBarbosatec** [comment]
Hi @tchex !
I think what i found this problem. Please could test again with `1.12.3` version.

**Comment by tchex** [comment]
Hi @RafaelBarbosatec !
Yes, no problem anymore. Thanks a lot !
