### ISSUE TITLE
State managers

### ISSUE THREAD

**Issue by Sproute777** [RafaelBarbosatec/bonfire#218]
Hello . Is it possible to add a state manager like flame_bloc , or your cubes with similar capabilities ?

 How to add more complex dependencies to the game?

 Or how to use your listeners?

**Comment by abgutierrez** [comment]
I think there's no way to use it as it is because BaseGame needs to extend FlameBlocGame and not FlameGame. Also, It's not easy but you can try to reimplement BaseGame class. I tried weeks ago, but later I decided to start using FlameBlocGame directly.
I'll try to do it again if no one starts implementing it, because now I want to use some bonfire features and manage the game state with BloC.

**Comment by Sproute777** [comment]
> I think there's no way to use flame_bloc it as it is on bonfire because BaseGame class needs to extend FlameBlocGame and not FlameGame. Also, It's not easy but you can try to reimplement BaseGame class. I tried weeks ago, but later I decided to start using FlameBlocGame directly. I'll try to do it again if no one starts implementing it, because now I want to use some bonfire features and manage the game state with BloC.

I added FlameBloc in pure Flame .  Game work correctly .
But Bonfire interfaces hide Flame , and not allow connect FlameBloc.

Game with a lot interfaces not good practice, too hard add new features , because need refactor too much .

**Comment by RafaelBarbosatec** [comment]
Hi guys! 
I started something related to state management in Bonfire. Something very embryonic. I would like you to take a look and tell me what you think and suggestions for improvements or modifications, or what really sucks this way. Hahaha.
This implementation you can find in example of this [branch](https://github.com/RafaelBarbosatec/bonfire/tree/state-manager-v2)

**Comment by RafaelBarbosatec** [comment]
Basically:

- Create your StateController:

```dart

class KnightController extends StateController<Knight> {

@override
  void onReady(Knight component) {
    // TODO: implement onReady
    super.onReady(component);
  }

  @override
  void onRemove(Knight component) {
    // TODO: implement onRemove
    super.onRemove(component);
  }
  
  @override
  void update(double dt) {
   // if (component?.checkInterval('seeEnemy', 250, dt) == true) {
    //   component?.seeEnemy(
    //     radiusVision: component!.width * 4,
    //     notObserved: _handleNotObserveEnemy,
    //     observed: (enemies) => _handleObserveEnemy(enemies.first),
    //   );
    // }
  }
}
```

- Put the dependencies and controllers:

```dart

BonfireInjector().put((i) => KnightController());
 // or
 // BonfireInjector().put(
  //   (i) => KnightController(),
  //   isSingleton: true,
  // );

```

- Adds mixin in your component:

```dart

class Knight extends SimplePlayer
    with Lighting, ObjectCollision, UseStateController<KnightController> {
}

```

**Comment by Sproute777** [comment]
Quite good , but I would like to use decoupled logic that can be connected to flutter .
this greatly simplifies the creation of buttons, scrolls and other interfaces.

**Comment by Sproute777** [comment]
separated blocks allow you to write more complex elements that can be tied to a regular flutter
![image](https://user-images.githubusercontent.com/76906744/156629396-ed8036b3-98f9-4d20-b055-7c12afa9c1e7.png)

**Comment by Sproute777** [comment]
I like ChangeNofifier . what if you follow a similar path and don't create blocks from ChangeNotifier they are fast and better suited for creating a game

**Comment by Sproute777** [comment]
![image](https://user-images.githubusercontent.com/76906744/156630834-c1ccd69a-b3d4-4f6a-ae8e-c039c2faa5c8.png)
stack positioned

**Comment by Sproute777** [comment]
![image](https://user-images.githubusercontent.com/76906744/156631248-407540f8-ec76-426d-8982-1a62bbf5232b.png)
Flutter + flame  => best_ui

**Comment by RafaelBarbosatec** [comment]
Great! I'll thought in the way to adds listeners in widgets. maybe we use ChangeNotifier!

In you Stack, you can use the param `overlayBuilderMap` in `BonfireTiledWidget` instead of `Stack`. like this:

```dart

return BonfireTiledWidget(
         ...
          overlayBuilderMap: {
            'settings':(context,game)=>MySettingsWidget(game),
          },
          initialActiveOverlays: [
            'settings'
          ],
        );

```

This way you can hide and show overlays dynamically:

```dart
gameRef.overlays.remove('settings'); // to hide
gameRef.overlays.add('settings');  // to show
```

**Comment by RafaelBarbosatec** [comment]
@Sproute777 !
Take a look here: [interface](https://github.com/RafaelBarbosatec/bonfire/tree/state-manager-v2/example/lib/shared/interface).
I made an example. on of a `BarLifeWidget ` listening the`BarLifeController` using `StateControllerConsumer `.

Tell me what you think. ☺️

**Comment by Sproute777** [comment]
I can try to use this solution , test .

**Comment by RafaelBarbosatec** [comment]
I will publish that as experimental. And i do a better documentation about this.
