### ISSUE TITLE
Thanks ,bonfire is great

### ISSUE THREAD

**Issue by wz19900616** [RafaelBarbosatec/bonfire#22]
like it very much

**Comment by wz19900616** [comment]
in demo ,Enemy didn't move to Player when it became unvisible, so how to make Enemy move to the Player when it is out of visible range?

**Comment by RafaelBarbosatec** [comment]
well, I didn't think about that situation, the idea is to get closer to what to see. you could increase the enemy's range of vision, maybe that can help you

**Comment by wz19900616** [comment]
thanks , it didn't work for me. I will try to find more solutions by free time.

**Comment by RafaelBarbosatec** [comment]
I'm sorry, now I understand your problem. This was fixed in version 0.3.3!
