### ISSUE TITLE
error trying to use Tiled map with margin/spacing

### ISSUE THREAD

**Issue by abgutierrez** [RafaelBarbosatec/bonfire#223]
Map is not correctly displayed when the Tileset file has margin/spacing defined. When I open map file or tileset on Tiled, everything works as expected, but running the game loads tiles incorrectly without using spacing between. Tileset class already obtains `spacing` and `margin` param from JSON file, but I think is not been used. Actually, I didn't find any method using these values. Any ideas?

**Comment by RafaelBarbosatec** [comment]
If you are trying to use these properties in tileset:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/10039275/154337326-bcb26742-b5f4-4edf-a170-569811cd4411.png">

The Bonfire is not have support for this yet.

**Comment by abgutierrez** [comment]
Sorry for the delay in responding, I was on vacation. @RafaelBarbosatec's reply answers my question. 

I will proceed to modify the implementation of the Tilesets loading in order to respect spacing and margins since it is required to keep margins and spacing of the Tilesets. We can close this issue.
