### ISSUE TITLE
TalkDialog.show() isn't changing character

### ISSUE THREAD

**Issue by TaylorHo** [RafaelBarbosatec/bonfire#224]
The TalkDialog.show() needs a `saylist` array/list as parameter, but when more than one `Say()` is passed **and** you change the `person` property of the `Say()`, the *text* changes, but the *person* not.

Example:
```
TalkDialog.show(
      context,
      [
        Say(
            text: [
              const TextSpan(
                  text: 'Some Text One'),
            ],
            person: SizedBox(
              child: CharacterOneWidget(),
              height: 100,
              width: 100,
            )),
        Say(
            text: [
              const TextSpan(text: 'Some Text Two'),
            ],
            person: SizedBox(
              child: CharacterTwoWidget(),
              height: 100,
              width: 100,
            ),
            personSayDirection: PersonSayDirection.LEFT),
      ]
    );
```

In this case, the dialog will be *"Some Text One"* (first) and then *"Some Text Two"* (second), it's ok, but the character doesn't change. In booth dialogs, the rendered character will be the *"CharacterOneWidget"*.

**Comment by RafaelBarbosatec** [comment]
Thanks for reporting!
I will take a look this problem.

**Comment by RafaelBarbosatec** [comment]
Hi @TaylorHo !
Bug fixed! This correction will be available in next version!
