### ISSUE TITLE
right way to display particles?

### ISSUE THREAD

**Issue by pmella16** [RafaelBarbosatec/bonfire#229]
hello I'm trying to show particles but I can't see them, I'm using the darkness_dungeon demo in the Knight class
I added the method

  @override
   void update(double dt) {
     super.update(dt);

     // Adds thruster particles.
     final particleComponent = ParticleComponent(
       Particle.generate(
         count: 10,
         life span: 1,
         generator: (i) => AcceleratedParticle(
           acceleration: Vector2(130.8183135986328, 311.3004455566406),
           speed: Vector2(100, 100),
           position: Vector2(130.8183135986328, 311.3004455566406),
           child: CircleParticle(
             radius: 1,
             paint: Paint()..color = Colors.red,
           ),
         ),
       ),
     );

     gameRef.add(particleComponent);
   }
are drawn below the map

![particulas abajo de tiled](https://user-images.githubusercontent.com/19208317/155376191-bec285e2-b62c-49bf-a138-5b3502ca574a.jpeg)

**Comment by RafaelBarbosatec** [comment]
Hi @pmella16 ! Thanks for reporting !
I recommend you create you own ParticleComponent class and do override the `priority` param. like this:
``` dart
class MyParticleComponent extends ParticleComponent{
  MyParticleComponent(Particle particle) : super(particle);
  
  @override
  int get priority => LayerPriority.MAP + 1;
}
```
and use them:

```dart
final particleComponent = MyParticleComponent(
   Particle.generate(
     count: 10,
     lifespan: 1,
     generator: (i) => AcceleratedParticle(
       acceleration: Vector2(130.8183135986328, 311.3004455566406),
       speed: Vector2(100, 100),
       position: Vector2(130.8183135986328, 311.3004455566406),
       child: CircleParticle(
         radius: 1,
         paint: Paint()..color = Colors.red,
       ),
     ),
   ),
 );

 gameRef.add(particleComponent);
```

I hope I've helped!

**Comment by pmella16** [comment]
> 

works like a charm, thanks
