### ISSUE TITLE
Does it support sanbox game?

### ISSUE THREAD

**Issue by winduajipras** [RafaelBarbosatec/bonfire#237]
Great work !! 
can we make sanbox game like minecraft with random map generator feature?

**Comment by RafaelBarbosatec** [comment]
Hi @winduajipras !
Maybe it's should be useful to this purpose:
https://github.com/RafaelBarbosatec/bonfire/pull/259

**Comment by winduajipras** [comment]
@RafaelBarbosatec 
🥰 This is what i want, make a dynamic map by changing matrix value

Thankyou Rafael
