### ISSUE TITLE
Can you make a small map of the scene, please?

### ISSUE THREAD

**Issue by chongbo2013** [RafaelBarbosatec/bonfire#244]
Can you make a small map of the scene, please?

**Comment by RafaelBarbosatec** [comment]
Hi @chongbo2013 !
I think that don't understand very well. 
We have some examples here: https://bonfire-engine.github.io/#/examples

**Comment by chongbo2013** [comment]
![image](https://user-images.githubusercontent.com/3191545/161187430-57d50bf7-ac43-4d6c-8618-f3a6d626d1df.png)

**Comment by RafaelBarbosatec** [comment]
Great! Got it!
I'll try build something like that to adds in Bonfire!
Thanks for idea!

**Comment by chongbo2013** [comment]
Haha thanks for going back and getting you some coffee

**Comment by RafaelBarbosatec** [comment]
![image](https://user-images.githubusercontent.com/10039275/162987595-794e6f99-73c2-40ae-abc2-72d3d218d7f7.png)

Bit by bit this feature show up! 😊

**Comment by RafaelBarbosatec** [comment]
Available in 2.4.1 version. Any suggestions or improvements, please  open PR.
[DOC](https://bonfire-engine.github.io/#/minimap)

**Comment by chongbo2013** [comment]
@RafaelBarbosatec  where  i am not found.

**Comment by TaylorHo** [comment]
@RafaelBarbosatec I think the question now is that the minimap documentation isn't showing anymore, see the "DOC" link you've sent in 2022.

@chongbo2013, Take a look at the [minimap widget](https://github.com/RafaelBarbosatec/bonfire/blob/master/lib/widgets/mini_map/mini_map.dart). You can add it to your map using an overlay, as in [this example](https://github.com/RafaelBarbosatec/bonfire/blob/cc530e757a8cb0bc28ba1a6688f4cf967012597b/example/lib/tiled_map/game_tiled_map.dart#L89-L96).

**Comment by chongbo2013** [comment]
> I don't put it in the documentation because is a experiment. I think that was not good yet. And the performance is not good too.

Thank you. How should I optimize it well?
