### ISSUE TITLE
Better "above" rendering

### ISSUE THREAD

**Issue by DevNico** [RafaelBarbosatec/bonfire#246]
Right now when a tile has the above property it always gets rendered above the player. Most of the time it should only get rendered above the player If the player is actually "behind" the object.

Would it be possible to support a more intelligent "above" rendering that takes the players position into account?

**Comment by RafaelBarbosatec** [comment]
All GameComponent added in the game have the behavior that you want. Try use objects in Tiled to add this objects.

**Comment by DevNico** [comment]
So instead of adding the above property I would need to add all the elements via an object layer and then using the `objectsBuilder`?

**Comment by RafaelBarbosatec** [comment]
An "above" property should actually have this behavior.  The behavior you expect is from a component in the game.  If you add any collisions to the tile on your map it will become a component in the game and will have this behavior waiting.

I'll see if you created a new property to have this behavior and no collision. Type "dynamicAbove"

**Comment by RafaelBarbosatec** [comment]
"dynamicAbove" available in 2.4.1 version. Any suggestions or improvements, please  open PR.
