### ISSUE TITLE
Problem starting widget

### ISSUE THREAD

**Issue by firmino2611** [RafaelBarbosatec/bonfire#258]
![Screenshot 2022-05-30 134357](https://user-images.githubusercontent.com/18086331/171033775-4ee65cb3-f946-45b5-8d48-ff9964edaa94.png)
![Screenshot 2022-05-30 134429](https://user-images.githubusercontent.com/18086331/171033840-e1d0fade-4fda-4469-afe9-8db47474baa7.png)

**Comment by RafaelBarbosatec** [comment]
You can share folder restructure when there is the map files?

Remembering that the map files as tileset have to be created in the same folder as the json maps. Otherwise can not find.
