### ISSUE TITLE
Enemies avoid collision obstacles

### ISSUE THREAD

**Issue by griotdonation** [RafaelBarbosatec/bonfire#272]
Hi thank you so much for such awesome code! Im trying to make the enemies follow the player but do so while avoiding collision obstacles. similar the MoveToPositionAlongThePath class with the player, but I cant get it work for the enemies. any help will be greatly greatly appreciated!

**Comment by RafaelBarbosatec** [comment]
Hi @griotdonation !
Thanks so much!
You tried use the `followComponent` method?

**Comment by griotdonation** [comment]
Hi Rafael!

Oh sorry, I don't think I gave this functionality a try for the enemy. I'll take a look. Thank you so much for you response.
