### ISSUE TITLE
Add line of sight for enemies

### ISSUE THREAD

**Issue by griotdonation** [RafaelBarbosatec/bonfire#273]
Is there any way to a Line of sight with enemies instead of a radiusVision? essentially, the enemies can only see what is in front of them within a specifically cone shaped area. Thanks so much in advanced!

**Comment by RafaelBarbosatec** [comment]
Hi @griotdonation !
Thanks for contacting!
In the moment it's not possible. But it's a good idea! I didn't have thinking about this yet. I will implement this feature.

**Comment by griotdonation** [comment]
Thank you so much Rafael!! This will be really helpful

**Comment by griotdonation** [comment]
> Hi @griotdonation !
> Thanks for contacting!
> In the moment it's not possible. But it's a good idea! I didn't have thinking about this yet. I will implement this feature.

Hi there, just wanted to know if you had an idea of when this feature may be released? No rush just curious to I can plan for my game project.

**Comment by RafaelBarbosatec** [comment]
Hi @griotdonation !
This feature will available in next release. I'm just do some improvements
