### ISSUE TITLE
How to set type above on tile layers

### ISSUE THREAD

**Issue by ahndwon** [RafaelBarbosatec/bonfire#274]
Hello, I'm trying to use type `above` for my Tiled maps.

But I think it can only be used on tiles. Not tile layers.
The docs are not really clear where type `above` is set. [docs](https://bonfire-engine.github.io/#/tiled_support?id=tiled-map-example)
Is it possible to set tile layers by above?

**Comment by RafaelBarbosatec** [comment]
Hi @ahndwon !
Thanks for contacting.
Is not possible set `above` in tile layer only in the tile.

**Comment by RafaelBarbosatec** [comment]
It's is a good idea. I will think how we can do this.

**Comment by ahndwon** [comment]
Thanks that will make developing beautiful Tiled maps much easier!!

**Comment by rafaelbarbosadrip** [comment]
Feature added in version 2.6.4.
Just create a Custom Property in your layer named `type` and value `above`.
<img width="296" alt="image" src="https://user-images.githubusercontent.com/108682683/179777733-96792c75-add0-4559-86d9-95f92904faed.png">
