### ISSUE TITLE
How to add collision by Tiled map?

### ISSUE THREAD

**Issue by ahndwon** [RafaelBarbosatec/bonfire#278]
Hi, I'm trying to make walls by Tiled map, but it seem's I can't add collision by custom properties.
Is there a way to add collision on tiles beside adding objects?

**Comment by RafaelBarbosatec** [comment]
Hi @ahndwon !
By Tiled you can add collision in tileset adding collision in a tile. Or you can add a object in you map and set your type to 'collision'.

https://bonfire-engine.github.io/#/tiled_support?id=useful

**Comment by ahndwon** [comment]
oops, sorry I think there's problem with my wall tiles. 
Adding collisions by Tiled collision editor is working with other tiles.
Thanks for the fast reply! I'll close the issue.
