### ISSUE TITLE
player animation for melee attack

### ISSUE THREAD

**Issue by griotdonation** [RafaelBarbosatec/bonfire#280]
Is there any way to update the player sprite animation when performing a melee attack? for example, the player animation will punch/kick as opposed to the whiteAttackEffectTop animation when pressing melee attack button,

**Comment by RafaelBarbosatec** [comment]
Hi @griotdonation !
Yes, it's possible. You can use animation.playOnce(newAnimation);

Take a look in this example:

https://github.com/RafaelBarbosatec/mini_fantasy

**Comment by griotdonation** [comment]
Thanks for your amazing and quick response!
