### ISSUE TITLE
Picking up collision decorations

### ISSUE THREAD

**Issue by griotdonation** [RafaelBarbosatec/bonfire#281]
Is there a possible way where the character can pick up a decoration with collision? For example if I wanted to player to jump on top of a barrel or pick up the barrel and hold it over his head?

**Comment by RafaelBarbosatec** [comment]
Yes, it's possible pick up a decoration.
In the player you can override 'onCollision' to know when and who is do collision with your player. And then, you can call some method I'm your decoration to do this decoration follow the player.
There is a mixin named 'Follower' that help you do your decoration follow you player.

**Comment by griotdonation** [comment]
I think I get it, let me give it a try! Thanks so much.
