### ISSUE TITLE
Sprite sheet animation that follow player

### ISSUE THREAD

**Issue by griotdonation** [RafaelBarbosatec/bonfire#282]
Hi, 

forgive me if this was answered already but I have a player and the sprite is designed to have no hands so  i can dynamically assign weapons to the player. these weapons are sprite sheet animations themselves. Im having trouble having this weapon animation follow the character as if its attached to his body. Please help if this is possible.

<img width="134" alt="image" src="https://user-images.githubusercontent.com/55745803/183229151-5d6401cd-f70d-4a04-84a5-d2b7bce3d23b.png">

**Comment by RafaelBarbosatec** [comment]
Hi @griotdonation!
We don't have anything to do this in the simple way. You must will think a way to do this.
If you can share these SpriteSheets I can try do something and share with you.

**Comment by griotdonation** [comment]
> 


Wow that'll be very much appreciated! Thank you, Rafael. Here are the sprite sheets. My end goal is to get a gun swivel effect similar to the game nuclear thrown.

![pistol](https://user-images.githubusercontent.com/55745803/183251020-180744e6-4338-4acc-a57e-04a2961aea3c.png)
![Character_9](https://user-images.githubusercontent.com/55745803/183251030-4f9eb389-2c97-4807-b823-f515396d0973.png)

Nuclear Throw example

![image](https://user-images.githubusercontent.com/55745803/183251254-0bb5e1d4-c206-45bd-a465-d051b08a72f7.png)

**Comment by RafaelBarbosatec** [comment]
Hi @griotdonation !
Sorry for my late.
Take a look if this work for you:
https://github.com/RafaelBarbosatec/game_player_gun_example

https://user-images.githubusercontent.com/10039275/183669664-fdf8daac-a3a7-4a53-949f-016063c40d28.mp4

**Comment by griotdonation** [comment]
No worries at all! Rafael, I cant thank you enough. this is awesome! thank you so much. I may make some small tweaks, for example to use the RADangle to shoot, to allow the player to shoot in the opposite direction he may be running in. for example, if zombies are chasing player, I'd want to move back while shooting.

Do you have "By me a coffee" account to something. really will like to show my gratitude!

**Comment by griotdonation** [comment]
Hi Raphael,

Im trying to resolve the playonce animation when moving, it appears the animation plays in the current position but doesn't follow the player while moving. Do you know how to resolve this issue

https://user-images.githubusercontent.com/55745803/184046819-908db5fc-04de-471e-911f-5009362938cf.mp4

?

**Comment by RafaelBarbosatec** [comment]
Hi @griotdonation !
I noticed this problem and updated that project. I even added this function in the UseSpriteAnimation mixin to make it easier.

**Comment by griotdonation** [comment]
Awesome!! I'll check it out, thanks, Raphael!

**Comment by RafaelBarbosatec** [comment]
Hi @griotdonation.
If you want encourage this work. You can contribute here:
https://www.buymeacoffee.com/rafaelbarbosa

**Comment by griotdonation** [comment]
> Hi @griotdonation.
> If you want encourage this work. You can contribute here:
> https://www.buymeacoffee.com/rafaelbarbosa

Will be making a contribution!
