### ISSUE TITLE
How to block move to position when user touches overlay interface when using JoystickMoveToPosition.

### ISSUE THREAD

**Issue by ahndwon** [RafaelBarbosatec/bonfire#283]
Hi, I'm using a modified JoystickMoveToPosition.
But when I touch the overlay interface,
due JoystickMoveToPosition, my character moves to position where i pressed on the overlay interface.

Is there a way to block joystick?? 
I want to only interact with overlay interface.

**Comment by RafaelBarbosatec** [comment]
Hi @ahndwon !

You are using the GameInterface or your interface is created with Widgets?

**Comment by ahndwon** [comment]
@RafaelBarbosatec  Thank's for the reply!
I'm using interface created by Widgets and also the MiniMap

**Comment by RafaelBarbosatec** [comment]
Humm. I have to do improvements about this. Don't let the gestures event pass to the game when received by widgets.

**Comment by ahndwon** [comment]
Yes that's right!

**Comment by ahndwon** [comment]
Wow, thanks @RafaelBarbosatec !!
That was fast🔥
I'll check it out and close this issue.
Thanks again!
