### ISSUE TITLE
Is there a way to hit multiple enemies?

### ISSUE THREAD

**Issue by Fixid-Fuzz** [RafaelBarbosatec/bonfire#286]
Is it possible to add range attacks to simpleAttackRange or simpleAttackMelee?
I want to hit multiple enemies with one skill. However, only the object that collides first takes damage.
Is there any way to add range attack?

**Comment by RafaelBarbosatec** [comment]
Hi @Fixid-Fuzz !
Yes, it's possible and already work. If the enemies have be in the attack both receive damage.
Maybe you need grown size of the attack.

**Comment by Fixid-Fuzz** [comment]
You were right.
melee attack confirmed that the range attack works normally.

In fact, what I wanted was to shoot a huge fireball and damage multiple people.

Tried testing with simpleAttackRangeByAngle, but still only got one hit.

Is it possible to perform a range attack by adding additional work to the onDestroy function of simpleAttackRangeByAngle?

**Comment by RafaelBarbosatec** [comment]
Great!
I will do improvements in range attack to apply damage in area of destroySize. I think what make sense!

**Comment by RafaelBarbosatec** [comment]
Available in `2.7.1` version

**Comment by Fixid-Fuzz** [comment]
Thank you so much.
I've verified that it works exactly as I wanted it to.
you are the best
