### ISSUE TITLE
click joystick, return directional MOVE_RIGHT

### ISSUE THREAD

**Issue by zhongzhuoan** [RafaelBarbosatec/bonfire#29]
In darkness_dungeon, When I click in the joystick area, function joystickChangeDirectional always return JoystickMoveDirectional.MOVE_RIGHT, even if event.intensity is 0.
eg: The knight walked to the left and stopped, When I click in the joystick area immediately turned to the right.

**Comment by RafaelBarbosatec** [comment]
Hi @zhongzhuoan !
Maybe I didn't get it right. But I tested it here and did not observe this behavior.

**Comment by zhongzhuoan** [comment]
maybe
in bonfire/lib/joystick/joystick_directional.dart
void update(double t) {
...
      if (degrees > -22.5 && degrees <= 22.5) {
        _joystickListener.joystickChangeDirectional(JoystickDirectionalEvent(
          directional: JoystickMoveDirectional.MOVE_RIGHT,
          intensity: _intensity,
          radAngle: _radAngle,
        ));
      }
...
}

When i touch the joystick and don't move, the degrees is 0, will call the above method. So callback JoystickMoveDirectional.MOVE_RIGHT.

**Comment by RafaelBarbosatec** [comment]
I identified. This improvement will be available in the next release!
