### ISSUE TITLE
Player running backwards

### ISSUE THREAD

**Issue by griotdonation** [RafaelBarbosatec/bonfire#290]
Hi Raphael,

Quick question. Im trying to get my player to shoot in the opposite direction in which he is running. essentially shooting while running backwards. My objective is is to use the radAngle to get my shooting direction, and essentially have the player face/shoot in that direction while running backwards in the opposite direction. is this possible with the current framework? Im guessing I would flip the idleRight sprite animation horizontally, but not finding an easy way to do. Thanks in advance!

**Comment by RafaelBarbosatec** [comment]
Yes, it's possible!
You can do attack to any direction.
Using 'simpleAttackRangeByAngle', only pass the radAngle that you want.

**Comment by RafaelBarbosatec** [comment]
Basically all it's possible. 🤣
Something has done in Bonfire to turn more easier. Other you can create your self, just need understand how game loop working.
Bonfire just makes your life easier with ready-made functions, components and behaviors

**Comment by griotdonation** [comment]
You're a god send! Thank you for all your help and for this awesome library
