### ISSUE TITLE
after 2.7.3 AnimatedFollowerObject issue

### ISSUE THREAD

**Issue by Fixid-Fuzz** [RafaelBarbosatec/bonfire#292]
Dear developer.
After patch 2.7.3
When an AnimatedFollowerObject overlaps a character, it does not appear on top of the character and appears behind it.

The logic seems to have changed regarding priorities.

Can I possibly set the priority of AnimatedFollowerObject?

Up to 2.7.2 it's perfect.

**Comment by RafaelBarbosatec** [comment]
Hi @Fixid-Fuzz !
Fix available in `2.7.4` version.

**Comment by Fixid-Fuzz** [comment]
You are the best.
Developing with your creations is so much fun.
Thank you for always.

**Comment by RafaelBarbosatec** [comment]
Thanks so much! 😊🤟
If you adds 'AnimatedFollowetObject' as player child you could also solve this problem.
Using add() instead of gameRef.add().

**Comment by Fixid-Fuzz** [comment]
> Thanks so much! 😊🤟 If you adds 'AnimatedFollowetObject' as player child you could also solve this problem. Using add() instead of gameRef.add().

Thank you!! I will take note
