### ISSUE TITLE
Update to Flame v1.3.0

### ISSUE THREAD

**Issue by KyleKun** [RafaelBarbosatec/bonfire#296]
Hi @RafaelBarbosatec , do you think it would be possible to update to v1.3.0 in this weekend so we can use Bonfire in the Flame Game Jam?

Thanks as always!

**Comment by rafaelbarbosadrip** [comment]
Hi @KyleKun!
I'm checking to see if there are any breaking changes that could impact

**Comment by RafaelBarbosatec** [comment]
Done!
