### ISSUE TITLE
moveToPositionAlongThePath method not working for Enemy class

### ISSUE THREAD

**Issue by Toda-Hora** [RafaelBarbosatec/bonfire#299]
When using the moveToPositionAlongThePath method to place an Enemy back at spawn it calculates the route but doesn't move the enemy to it.

**Comment by rafaelbarbosadrip** [comment]
Hi @Toda-Hora !
I cannot reproduce this problem. can you give me more information?

**Comment by Fixid-Fuzz** [comment]
> Hi @Toda-Hora ! I cannot reproduce this problem. can you give me more information?

I had a similar case.
This function does not work when the enemy is not on the screen.

I tried to use it this way, but it didn't work, so I'm using it in another way.

**Comment by RafaelBarbosatec** [comment]
Yes, only work to visible objects. But I can adds a param tem enable this.

**Comment by Fixid-Fuzz** [comment]
> Yes, only work to visible objects. But I can adds a param to enable this.

awesome!! If so, I would be very happy.
