### ISSUE TITLE
Is it possible to resolve the monster collision in the seeAndMoveToPlayer?

### ISSUE THREAD

**Issue by Fixid-Fuzz** [RafaelBarbosatec/bonfire#301]
Use seeAndMoveToPlayer to move monsters to the player.

However, due to the large size of the collision, if monsters collide with each other before reaching the player, they do not move.

If they collide, can you re-approach them in different paths?

**Comment by RafaelBarbosatec** [comment]
Hi @Fixid-Fuzz !
This method not use FindPath Algorithm. He tries to approach using something simpler. He even tries to dodge obstacles depending on the situation.

**Comment by Fixid-Fuzz** [comment]
> Hi @Fixid-Fuzz ! This method not use FindPath Algorithm. He tries to approach using something simpler. He even tries to dodge obstacles depending on the situation.

https://user-images.githubusercontent.com/99014005/186191272-959c6646-e754-47ed-9fe2-459a393f1ccc.mov

When I use followComponent in the seeAndMoveToPlayer function, it often happens that the enemy does not follow and stops.
It seems that the enemy is trying to go to the same coordinates. Is there any way I can do to solve it?

If there is no other way than to use FindPath Algorithm, I'll fix it that way.

**Comment by Fixid-Fuzz** [comment]
I'm so sorry I have so many things I want from God.

**Comment by RafaelBarbosatec** [comment]
Interesting. I will analyze this. This wasn't supposed to happen.

**Comment by rafaelbarbosadrip** [comment]
Strange in this example: https://bonfire-engine.github.io/examples/bonfire/#/ (Simple example) this not happen.

**Comment by Fixid-Fuzz** [comment]
class CryptGoblin extends SimpleEnemy with ObjectCollision {
  final Vector2 initPosition;
  double attack = 20;

  CryptGoblin(this.initPosition)
      : super(
    animation: EnemySpriteSheet.goblinAnimations(),
    position: initPosition,
    size: Vector2.all(tileSize * 1.5),
    speed: tileSize / 0.35,
    life: 120,
  ) {
    setupCollision(
      CollisionConfig(
        collisions: [
          CollisionArea.rectangle(
            size: Vector2(
              tileSize,
              tileSize,
            ),
            align: Vector2(tileSize/3, tileSize/2),
          ),
        ],
      ),
    );
  }

  @override
  void render(Canvas canvas) {
    drawDefaultLifeBar(
      canvas,
      borderRadius: BorderRadius.circular(2),
    );
    super.render(canvas);
  }

  @override
  void update(double dt) {
    super.update(dt);

    seeAndMoveToPlayer(
      closePlayer: (player) {
        execAttack();
      },
      radiusVision: tileSize * 4,
    );
  }

  @override
  void die() {
    gameRef.add(
      AnimatedObjectOnce(
        animation: CommonSpriteSheet.smokeExplosion,
        position: position,
        size: Vector2(32, 32),
      ),
    );
    removeFromParent();
    super.die();
  }

  void execAttack() {
    simpleAttackMelee(
      size: Vector2.all(tileSize * 0.62),
      damage: attack,
      interval: 800,
      animationRight: EnemySpriteSheet.enemyAttackEffectRight(),
      execute: () {
        Audio.meleAtackPlayer();
        gameRef.player?.receiveDamage(AttackFromEnum.ENEMY, attack, 0);
      },
    );
  }

  @override
  void receiveDamage(AttackFromEnum attacker, double damage, dynamic id) {
    showDamage(
      damage,
      config: const TextStyle(
        fontSize: 14,
        color: Colors.white,
        fontFamily: 'Normal',
      ),
    );
    super.receiveDamage(attacker, damage, id);
  }
}

**Comment by Fixid-Fuzz** [comment]
I only fixed the collision size in your code.

https://github.com/RafaelBarbosatec/darkness_dungeon

**Comment by rafaelbarbosadrip** [comment]
@Fixid-Fuzz try grow `margin` in `seeAndMoveToPlayer `

**Comment by rafaelbarbosadrip** [comment]
What version of Bonfire you are using.

**Comment by rafaelbarbosadrip** [comment]
I have that do update this game: `https://github.com/RafaelBarbosatec/darkness_dungeon`.

**Comment by Fixid-Fuzz** [comment]
> What version of Bonfire you are using?

i updated to 2.9.0.

**Comment by Fixid-Fuzz** [comment]
[darkness_dungeon_bonfire2.9.0.zip](https://github.com/RafaelBarbosatec/bonfire/files/9409550/darkness_dungeon_bonfire2.9.0.zip)

I'm so sorry.
Fixed collision sizes and maps for better reproduction.
I can't fix bugs due to lack of skills.
Thank you so much for your support.

**Comment by Fixid-Fuzz** [comment]
> [darkness_dungeon_bonfire2.9.0_fix.zip](https://github.com/RafaelBarbosatec/bonfire/files/9409612/darkness_dungeon_bonfire2.9.0_fix.zip)
> 
> I'm so sorry. Fixed collision sizes and maps for better reproduction. I can't fix bugs due to lack of skills. Thank you so much for your support.

https://user-images.githubusercontent.com/99014005/186234546-7c873e63-f3c7-4f2d-89f8-b6324f9ef5f4.mov

**Comment by Fixid-Fuzz** [comment]
한가지 방법을 생각해봤습니다.
제가 생각하기에 멈추는 이유는 적끼리 충돌 때문입니다.
그래서 만약 적끼리 부딛힌다면 runRandomMovement를 부여해서 움직이게 하면 해결 될 것 같습니다.

아래 코드는 제가 해결해 본 방법입니다.
부족한 점이 있으면 지적 부탁드립니다.

    import 'package:bonfire/bonfire.dart';
    import 'package:darkness_dungeon/main.dart';
    import 'package:darkness_dungeon/util/enemy_sprite_sheet.dart';
    import 'package:darkness_dungeon/util/functions.dart';
    import 'package:darkness_dungeon/util/game_sprite_sheet.dart';
    import 'package:darkness_dungeon/util/sounds.dart';
    import 'package:flutter/material.dart';
    
    class Goblin extends SimpleEnemy with ObjectCollision, AutomaticRandomMovement {
      final Vector2 initPosition;
      double attack = 25;
    
      Goblin(this.initPosition)
          : super(
              animation: EnemySpriteSheet.goblinAnimations(),
              position: initPosition,
              size: Vector2.all(tileSize * 1.5),
              speed: tileSize / 0.35,
              life: 120,
            ) {
        setupCollision(
          CollisionConfig(
            collisions: [
              CollisionArea.rectangle(
                size: Vector2(
                  valueByTileSize(7),
                  valueByTileSize(7),
                ),
                align: Vector2(valueByTileSize(3), valueByTileSize(4)),
              ),
            ],
          ),
        );
      }
    
      @override
      void render(Canvas canvas) {
        this.drawDefaultLifeBar(
          canvas,
          borderRadius: BorderRadius.circular(2),
        );
        super.render(canvas);
      }
    
      bool onCol = false;
      bool onColEnd = false;
      double mdt = 0;
    
      @override
      void update(double dt) {
        mdt = dt;
        super.update(dt);
    
        if (onCol == false) {
          this.seeAndMoveToPlayer(
            closePlayer: (player) {
              execAttack();
              onColEnd = true;
              Future.delayed(const Duration(milliseconds: 300), () {
                onColEnd = false;
              });
            },
            observed: () {
    
            },
            radiusVision: tileSize * 4,
          );
        } else {
          randomMove();
        }
      }
    
      @override
      void die() {
        gameRef.add(
          AnimatedObjectOnce(
            animation: GameSpriteSheet.smokeExplosion(),
            position: this.position,
            size: Vector2(32, 32),
          ),
        );
        removeFromParent();
        super.die();
      }
    
      void execAttack() {
        this.simpleAttackMelee(
          size: Vector2.all(tileSize * 0.62),
          damage: attack,
          interval: 800,
          animationRight: EnemySpriteSheet.enemyAttackEffectRight(),
          execute: () {
            Sounds.attackEnemyMelee();
          },
        );
      }
    
      @override
      void receiveDamage(AttackFromEnum attacker, double damage, dynamic id) {
        this.showDamage(
          damage,
          config: TextStyle(
            fontSize: valueByTileSize(5),
            color: Colors.white,
            fontFamily: 'Normal',
          ),
        );
        super.receiveDamage(attacker, damage, id);
      }
    
      @override
      bool onCollision(GameComponent component, bool active) {
        // TODO: implement onCollision
    
        if (onColEnd == false && onCol == false &&
            component.runtimeType.toString() != 'TileWithCollision' &&
            component.runtimeType.toString() != 'Knight') {
          print('coll :: ${component.runtimeType.toString()}');
          onCol = true;
          Future.delayed(Duration(milliseconds: 600), () {
            onCol = false;
          });
        }
        return super.onCollision(component, active);
      }
    
      void randomMove() {
        print('rand!');
        if (isDead == false) {
          runRandomMovement(
            mdt,
            speed: speed,
            maxDistance: (scaledSize.x * 2).toInt(),
            minDistance: (scaledSize.x * 2).toInt(),
            timeKeepStopped: 300,
          );
        }
      }
    }

**Comment by RafaelBarbosatec** [comment]
Hi @Fixid-Fuzz !
This is a really very specific case. the two synchronously try to occupy the same space. Like two fools trying to get through the door at the same time 😂. I made a small improvement and if it can't move it will be called `notObserved`. So if you put a runRandomMovement in it it should solve.

**Comment by Fixid-Fuzz** [comment]
You made it simple and clear.
Thank you very much.
