### ISSUE TITLE
seeAndMoveToPlayer feature suggestion

### ISSUE THREAD

**Issue by Fixid-Fuzz** [RafaelBarbosatec/bonfire#303]
thank you!!
I confirmed that you updated seeAndMoveToPlayer.

Being notObserved even though the enemy is actually visible is likely to cause problems later.

Obstacle obstaclecollision?.call(); instead of notObserved?.call();
How about adding something like that?

Could you please add an option like 'obstaclecollision' for exceptional circumstances?

    seeAndMoveToPlayer({
        obstaclecollision: () {}
        observed: () {}
        notObserved: () {}
    })

**Comment by Fixid-Fuzz** [comment]
> Great ideia. I will update this method


It seems to be bothering you, so I closed the issue and was looking for a better way.
Thank you for your help as always.

**Comment by RafaelBarbosatec** [comment]
Available in version 2.9.2

**Comment by Fixid-Fuzz** [comment]
> Available in version 2.9.2

You are the best always!!
