### ISSUE TITLE
platformer example?

### ISSUE THREAD

**Issue by beanhead217** [RafaelBarbosatec/bonfire#304]
Hi,

thank you so much for this awesome code. I'd like to create a platformer-style game, like the Mario brothers. I don't see any examples for a platformer, is there any existing friendly code already existing that will allow me to easily implement this? for example horizontal movement only and jumping?

**Comment by rafaelbarbosadrip** [comment]
Hi @beanhead217 !
This package is focused in create games top-down. To create platformer-style game i recommend use the [Flame](https://flame-engine.org/) pure

**Comment by beanhead217** [comment]
Understood thank yoi
