### ISSUE TITLE
Dragable Map

### ISSUE THREAD

**Issue by TaylorHo** [RafaelBarbosatec/bonfire#309]
Is it possible to create a dragable map?

**Comment by RafaelBarbosatec** [comment]
We can do this happen.
You have some reference or example to send me?

**Comment by RafaelBarbosatec** [comment]
Try this with the new version.

**Comment by TaylorHo** [comment]
It's worked! Thanks a lot!

I've extended `MouseGesture` too, adding a zoom feature in the map :)
