### ISSUE TITLE
In 2.9.4 version, Attackable requests.

### ISSUE THREAD

**Issue by Fixid-Fuzz** [RafaelBarbosatec/bonfire#312]
In 2.9.4, Attackable has no set life.

Could you please add set life again?

I'm making a game where you fight by changing multiple characters, and each character has a different life.

I used the set life function when changing characters, but now it's gone, so it's a difficult situation.

I tried to cope with set life with updateLife applied to 2.9.4, but when a character dies, I coded another character to come out instead of die, but now it dies because there is no set life.

Could you please return the set life feature to Attackable in the next version?

**Comment by Fixid-Fuzz** [comment]
Neither addLife nor updateLife can specify the moment a character dies.

**Comment by RafaelBarbosatec** [comment]
I understand. but only it's call `die` in `removeLife`. And you can do override in `die` method and not call the `super.die` to not die.

**Comment by Fixid-Fuzz** [comment]
I hadn't thought of overriding it.
Thank you. Let's proceed like that.

**Comment by rafaelbarbosadrip** [comment]
Thanks so much for this issue. But would be strange I permit Editing life without verify if revive or die.

**Comment by Fixid-Fuzz** [comment]
> 

I couldn't check verifyDieOrRevive in updateLife in Attackable.

Thank you for always making great engines.
