### ISSUE TITLE
8 direction x axis flipping

### ISSUE THREAD

**Issue by beanhead217** [RafaelBarbosatec/bonfire#316]
Hi there,

Wonderful code! I have  a question regarding 8 direction . Is it easily possible to flip X-axis of runUpRight and runDownLeft like it’s done runRight? This will save me having to create additional sprite sheets for left animations.

**Comment by RafaelBarbosatec** [comment]
Hi @beanhead217 . 
Thanks so much!
I think that is possible! I'll working in this. ☺️

**Comment by RafaelBarbosatec** [comment]
Feature available in version 2.10.3.
