### ISSUE TITLE
Repository for sunny place ?

### ISSUE THREAD

**Issue by griotdonation** [RafaelBarbosatec/bonfire#323]
Hi there, 

Is there a GitHub repository for sunny place?

**Comment by RafaelBarbosatec** [comment]
Hi @griotdonation !
I'm sorry, Sunny Place is my personal project. I'm building it little a little. 😊

**Comment by griotdonation** [comment]
> Hi @griotdonation !
> I'm sorry, Sunny Place is my personal project. I'm building it little a little. 😊

Ah I see! No worries at all 😄 thanks for the reply!
