### ISSUE TITLE
Turn based Enemy and player movement

### ISSUE THREAD

**Issue by beanhead217** [RafaelBarbosatec/bonfire#324]
Hi Rafael,

I'm looking to build a turn-based RPG using bonfire, I see the tap screen to move feature has been added. is there anything that exists to add the same AI movement to enemies and limit the tile spaces that can be moved (similar to chest)? I've attached a photo for reference. Thanks is advance brother!
![image](https://user-images.githubusercontent.com/112144591/192125390-03309da9-f7f5-46ca-b253-bdb0c2363c99.png)

**Comment by RafaelBarbosatec** [comment]
Hi @beanhead217 !
The Bonfire have no AI implementation. But you can search for some algorithm to this and use the movements methods available in Bonfire.

**Comment by griotdonation** [comment]
Thank you so much!! I'll look into it!

**Comment by beanhead217** [comment]
Thanks so much!
