### ISSUE TITLE
Mnimap zoom

### ISSUE THREAD

**Issue by GyHUN95** [RafaelBarbosatec/bonfire#325]
Dear Rafael, sorry for botherng you with these little questions, but I recently noticed, that MiniMap use the default game zoom and sometimes it's miss some edge of the map: 
![image](https://user-images.githubusercontent.com/44195762/192215703-23958606-7eea-4666-ab9b-c10e29270706.png)

In my case, nowadays testing some 16x16 spritesheets and I need a bigger zoom (3-5).
Suggestion: Minimap always center player and use zoom: 1 as default independently from the BonfireWidget (I tried to resize the minimap a lot, but in the end it covers half of my screen is I use zoom > 1).

**Comment by RafaelBarbosatec** [comment]
I didn't can configure the MiniMap zoom yet. I will try find out some solution for this. if could might help me with this i'll stay super glade. ☺️
This is the file: bonfire/lib/widgets/mini_map/mini_map_canvas.dart

**Comment by RafaelBarbosatec** [comment]
Available in Version 2.10.10.
