### ISSUE TITLE
Using multiple/layered spritesheets

### ISSUE THREAD

**Issue by GyHUN95** [RafaelBarbosatec/bonfire#326]
Dear Rafael, I know it's a really noob question, but has Bonfire any layered SpriteSheet support? I'm testing spritesheets, like this: image 1: body, image2: hair, image3: cloth. I found this section, but unfortunately didn't work in the newest version:
https://bonfire-engine.github.io/#/loading_assets?id=mergin-images
I can provide the original spritesheets if it's help.

Thank you for your time!

**Comment by rafaelbarbosadrip** [comment]
You can get some spritesheets to do it here: https://github.com/RafaelBarbosatec/bonfire/tree/master/example/assets/images/lpc
