### ISSUE TITLE
directionThePlayerIsIn() seems a bit odd.

### ISSUE THREAD

**Issue by Fixid-Fuzz** [RafaelBarbosatec/bonfire#327]
directionThePlayerIsIn() seems a bit odd.

In the directionThePlayerIsIn() function you made to find the direction the player is in, the conditional statement is x, and it compares it with y.

the code below

      if (diffPositiveX > diffPositiveY) {
        if (player.center.x > center.y) {
          return Direction.right;
        } else if (player.center.x < center.y) {
          return Direction.left;
        }
      } else {
        if (player.center.y > center.x) {
          return Direction.down;
        } else if (player.center.y < position.x) {
          return Direction.up;
        }
      }

It should be something like below.
I'm sorry if I'm wrong.

      if (diffPositiveX > diffPositiveY) {
        if (player.center.x > center.x) {
          return Direction.right;
        } else if (player.center.x < center.x) {
          return Direction.left;
        }
      } else {
        if (player.center.y > center.y) {
          return Direction.down;
        } else if (player.center.y < position.y) {
          return Direction.up;
        }
      }

**Comment by RafaelBarbosatec** [comment]
Hi @Fixid-Fuzz !
Thanks so much for open this issue. Make sense that you said. I will do this correction.
