### ISSUE TITLE
Turn based strategy

### ISSUE THREAD

**Issue by fairmount88217** [RafaelBarbosatec/bonfire#328]
Hi there Rafael,

Sorry to bother and thank you for this repository its amazing! i was going through your issues and the below style game but in examples. I would like to create turn based strategy game but not sure how to implement the tile coloring based on distance allowed for each player and switch turn. would you be able to help with his request? definitely will show gratitude via "Buy me a coffee"

<img width="420" alt="image" src="https://user-images.githubusercontent.com/114515922/192598309-a53d9c16-ef58-4f16-a9ac-2c2d943ff958.png">

<img width="309" alt="image" src="https://user-images.githubusercontent.com/114515922/192598405-fbae6110-49f0-4081-8e2e-6fe53e247f7e.png">

**Comment by RafaelBarbosatec** [comment]
Hi @fairmount88217 !
Interesting  game case. I'll separate a time to try create an example that how create a type of the game.
If i find things that seems be good and util to this game type, I'll adds to the Bonfire.

**Comment by griotdonation** [comment]
Omg, thanks so much @RafaelBarbosatec !! Can't wait to see the implementation

**Comment by RafaelBarbosatec** [comment]
Hi @fairmount88217 !
I don’t paid attention in all of details but i hope this can help you!

https://user-images.githubusercontent.com/10039275/193309222-38fbad11-3b7f-4974-981e-1a666754702e.mp4

[Example](https://github.com/RafaelBarbosatec/turn_game)

**Comment by fairmount88217** [comment]
forget the details, this is awesome!! Thank you @RafaelBarbosatec buying you a coffee right now! really appreciate your help.

**Comment by fairmount88217** [comment]
Enjoy the well deserved coffee!

**Comment by fairmount88217** [comment]
hey Rafael,

Sorry to bother again, I'm playing around with the code and just spent the past few hours trying to figure how to make this small change. I figured I'd ask since the code may still be fresh in your mind, hoping you can help. but I see that the player can either move or attack. I was looking both, basically the player moves and then they can attack or see attack range of after having made a move.

**Comment by RafaelBarbosatec** [comment]
Hi @fairmount88217 !
So, in this example the players can move or attack. This you already got it.
There's two areas, the white squares (this is a grid that control to where the player can move) and the red circles (this is the grid that indicate the area what can do attack, if the opponent stay in this area can receive attack when clicked.

**Comment by fairmount88217** [comment]
> Hi @fairmount88217 ! So, in this example the players can move or attack. This you already got it. There's two areas, the white squares (this is a grid that control to where the player can move) and the red circles (this is the grid that indicate the area what can do attack, if the opponent stay in this area can receive attack when clicked.

Correct, but i see the turn switches when a move or an attack happens. Is it possible to have the player do both before turn is over. So they will move (show white squares first) and then attack (show red dots only), as this will give them more ground to cover from their initial position. let me know if this make sense, sorry.

**Comment by RafaelBarbosatec** [comment]
Yes, it's possible. You'll need control this of some way in the PlayerTurn.
In this class when is finished the moviment (along the path) I called the method in the turnManager to change the turn. You only need change this moment that call changeTurn.

**Comment by fairmount88217** [comment]
Awesome! I'll continue to study the code. thanks for giving me a point of reference.

**Comment by fairmount88217** [comment]
Hi raphael, 

one quick question. Im trying to use the followWidget component for the players it the game, I see plater_turn extends a class of NPC. Would you happen to know how can i find the NPC or active player GameComponent?

   FollowerWidget.show(
      identify: 'PLAYER_INVENTORY', // identify used to remove
      context: context,
      target: player, // You can add here any GameComponent
      child: MyWidget(), // Add here your widget
      align: Offset.zero, // Align from targe
   );

**Comment by fairmount88217** [comment]
Actually found the answer. I users gameRef.camera.target! thanks!

**Comment by RafaelBarbosatec** [comment]
Hi @fairmount88217 !
In the turnManager you can find the player active too

**Comment by fairmount88217** [comment]
did you mean like this, but still not getting follower widget. the gameRef.camera.target stopped working if the camera was scrolled.
![image](https://user-images.githubusercontent.com/114515922/193456580-80ab5d3c-39e0-410a-b0c9-a1975d8c0b5c.png)

**Comment by fairmount88217** [comment]
think i have it here
![image](https://user-images.githubusercontent.com/114515922/193458478-9efb5b60-a370-48fc-9630-6492a780ea8c.png)
