### ISSUE TITLE
Inquire about adding the showDamage function

### ISSUE THREAD

**Issue by Fixid-Fuzz** [RafaelBarbosatec/bonfire#330]
In bonfire I can style the text with config in show Damage.
However, it would be nice to be able to set outline and gradient in order to express damage dynamically.

Could you please add outline and gradient settings to showDamage?

**Comment by RafaelBarbosatec** [comment]
Hi @Fixid-Fuzz !
This would be awesome !
But Bonfire use the Flame API for this. We need wait this implementation of they!
You could open this issue in the Flame repository.
[Flame Doc](https://docs.flame-engine.org/1.4.0/flame/rendering/text.html)
[Flame Examples](https://examples.flame-engine.org/#/)
