### ISSUE TITLE
Set transparent background color?

### ISSUE THREAD

**Issue by ahndwon** [RafaelBarbosatec/bonfire#334]
Hello, I want to overlay bonfire over my Flutter app.
But it seems I can only set background by `GameBackground` class.
When I set transparent color to GameBackground class, the background is black.

Can you make a `backgroundColor` property to BonfireWidget 
which sets color to `GameWidget` by overriding `backgroundColor` method?

Or is there a way to set transparent background?

**Comment by RafaelBarbosatec** [comment]
Hi @ahndwon !
Thanks for contacting !
This param will be available in next release `backgroundColor`.

**Comment by ahndwon** [comment]
Wow thanks!
I really appreciate it.
I'll check it out right now.
