### ISSUE TITLE
Can not use keyboard  after touching overlayBuilderMap

### ISSUE THREAD

**Issue by sonhoai27** [RafaelBarbosatec/bonfire#339]
Thanks for the great work.
I have an issue when I touched into overlayBuilderMap. I create an item of overlayBuilderMap with StatefulWidget and I can not use the keyboard to direct a Player after touching or clicking this item.

`bonfire: ^2.11.2`

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.6, on macOS 13.0.1 22A400 darwin-arm, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
[✓] VS Code (version 1.73.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by RafaelBarbosatec** [comment]
Hi @sonhoai27 !
Could you give more detail about your overlay? Probably your overlay get the focus. I guess that it's the problem.

**Comment by RafaelBarbosatec** [comment]
Hi @sonhoai27 ! 
Thanks so much! 😊😉
I will analise how we can do this and share here as possible.

**Comment by sonhoai27** [comment]
Hi @RafaelBarbosatec
Thank you too.
I have created a test overlayBuilderMap like this
![image](https://user-images.githubusercontent.com/19631102/201516714-a2f37c05-25f4-4b8c-ad5d-36a14aecf122.png)

and when I clicked or touched this container, The Game lost focus.

I have cloned this repo [https://github.com/RafaelBarbosatec/mountain_fight](url) and test and  it also like me - lost focus

**Comment by RafaelBarbosatec** [comment]
Hi @sonhoai27 !
It’s Strange, I didn’t  can reproduce this. I just reproduce this behavior when I use a TextField in the overlay. And in this case is correct lost focus.
You can pass a `Focus` in `BonfireWidget` case it’s necessary to request focus.
If you can share anything else that help reproduce this problem. It would be good.

**Comment by sonhoai27** [comment]
Hi @RafaelBarbosatec
Thank you, I have resolved this issue by using the focus node.
