### ISSUE TITLE
Is Bonfire suitable for a game like Queen's Wish?

### ISSUE THREAD

**Issue by vinidiktov** [RafaelBarbosatec/bonfire#340]
Hi, I was wondering if Bonfire is well-suited for creating  turn-based RPGs in the style of Queen's Wish: The Conqueror?

http://www.spiderwebsoftware.com/queenswish/

![Outdoors1920x1080](https://user-images.githubusercontent.com/75051/201526531-a315c678-d649-4e28-be7d-72dcb8d45848.jpg)
![Council1920x1080](https://user-images.githubusercontent.com/75051/201526538-fc893166-69e5-4da1-a7c0-a483a89fff86.jpg)
![BuyBuilding1920x1080](https://user-images.githubusercontent.com/75051/201526540-0b6f7314-16d9-49af-b605-4fda1f2b72e1.jpg)
![Attackdragon1920x1080](https://user-images.githubusercontent.com/75051/201526541-0386c685-6467-42c1-a8f0-6f2112992260.jpg)

**Comment by RafaelBarbosatec** [comment]
Hi @vinidiktov !
I created a example that how you can create a game like this.
Take a look! I hope that it's could be helpful.

 https://rafaelbarbosatec.itch.io/turn-game

**Comment by vinidiktov** [comment]
So, the answer is yes.

Thanks, Rafael.
