### ISSUE TITLE
Camera showOnlyMapArea shows black area at the right and bottom of screen

### ISSUE THREAD

**Issue by KyleKun** [RafaelBarbosatec/bonfire#347]
When set to true, this property seems to work only on the top and left of the screen.
I'll investigate this.

**Comment by RafaelBarbosatec** [comment]
The default backgroundColor is black.

**Comment by KyleKun** [comment]
> The default backgroundColor is black.

Yes, but I think the expected behavior would be to automatically zoom in the map until the background isn't visible. This way it would make more sense the name of the param, and show only the map area. I will try to submit a PR later!

**Comment by RafaelBarbosatec** [comment]
Could you share a screenshot of your case?

**Comment by KyleKun** [comment]
Example where this happens: https://kylekun.itch.io/pikpik

When you walk, the bottom and right show the black background, but I wish to show only the map on the screen.

**Comment by RafaelBarbosatec** [comment]
Fixed in 2.11.8 version ☺️!
Thanks so much for report this issue.

**Comment by KyleKun** [comment]
Works like a charm, thank you once again!
