### ISSUE TITLE
Enemies getting stuck in collisions sometimes

### ISSUE THREAD

**Issue by KyleKun** [RafaelBarbosatec/bonfire#354]
In the official example (and also my game), enemies that use the AutomaticRandomMovement mixin sometimes get stuck or even past tiled collisions, like this:

![issue_collision](https://user-images.githubusercontent.com/36611739/206867294-449c937a-49c3-4367-8755-9271cb58ac23.png)

Any ideas how we could solve it?

(By the way, the example is not updated with recent changes merged into master)

**Comment by RafaelBarbosatec** [comment]
Hi @KyleKun !
Thanks for this report. I’m have analyzing this problem.

**Comment by RafaelBarbosatec** [comment]
Please, check again using the new version available. 😊
