### ISSUE TITLE
Opacity is ignored for Tiled layers

### ISSUE THREAD

**Issue by SoSayethSimon** [RafaelBarbosatec/bonfire#356]
Thanks for this project - it's a lot of fun and intuitive to use 👍

Right now i'm experimenting with Tiled Maps and noticed that opacity for a layer seems to be ignored or is not implemented yet.

here is the json of the layer with opacity set to 0:
![json](https://user-images.githubusercontent.com/14994398/208236493-84c71fed-820c-43f6-a520-a0b63ac23a50.png)

Ingame the layer is drawn without opacity (in this case the column my knight is leaning against):
![ingame](https://user-images.githubusercontent.com/14994398/208236438-c2c1abab-876f-45a7-99b5-5b599ec98e72.png)

There are other workarounds if you want to do transparent collisions, but the different opacity scalings might also be useful for other usecases.

**Comment by RafaelBarbosatec** [comment]
Hi @SoSayethSimon !
Thanks for this report.
I'll implement the opacity in the layer.
If you need adds collision by Tiled. You can add a Object and set class egual 'collision'.
