### ISSUE TITLE
Multiplayer local online 

### ISSUE THREAD

**Issue by chongbo2013** [RafaelBarbosatec/bonfire#357]
Hello, can you support the ability of multiplayer local online?

**Comment by RafaelBarbosatec** [comment]
Hi @chongbo2013 !
It’s possible. There are some examples in the internet and videos in youtube teaching how create a multiplayer game using Socket.io. You can use `nakama` too.
https://github.com/RafaelBarbosatec/mountain_fight
https://www.youtube.com/watch?v=VXRx3N5M4Y0

**Comment by minchemo** [comment]
https://github.com/obrunsmann/flutter_nakama
There's a flutter_nakama package which I am using with bonfire, it's easily to use.
