### ISSUE TITLE
simpleAttackRange duration

### ISSUE THREAD

**Issue by minchemo** [RafaelBarbosatec/bonfire#361]
```dart
component!.simpleAttackRangeByDirection(
              onDestroy: () {},
              animationRight: SpriteAssets.getOnlyCollisionAnimation(),
              speed: 100,
              size: Vector2.all(8),
              direction: component!.lastDirection,
              attackFrom: AttackFromEnum.PLAYER_OR_ALLY);
```
Currently it seems to last indefinitely if it doesn't collide with anything, does able to set duration or max distance for range attack animation ?

**Comment by RafaelBarbosatec** [comment]
Hi @minchemo !
In the moment there isn’t how set duration or max distance.
This method adds in the game a `FlyingAttackObject`. You can create you own extending by  `FlyingAttackObject and adding your behavior.
