### ISSUE TITLE
Hello, I have seen the demo map, but there is no place to set collision, and the collision parameters added cannot be used

### ISSUE THREAD

**Issue by chongbo2013** [RafaelBarbosatec/bonfire#363]
Hello, I have seen the demo map, but there is no place to set collision, and the collision parameters added cannot be used
![image](https://user-images.githubusercontent.com/3191545/209430768-f9e5abb6-8719-4537-9159-b7da9d3fdc76.png)

**Comment by chongbo2013** [comment]
I haven't set any collisions. Why can't the character walk

**Comment by RafaelBarbosatec** [comment]
If you need set collisions in your tileset. you need open the tileset detail select the tile and configure the collision:

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/10039275/209445281-6ec11aa0-3a48-455f-b0e3-373a1f9f4b0a.png">

Another way to add collision is using objects. you can create a Object Layer and adds objects. you must set the `class` to `collision`:

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/10039275/209445345-e20b284e-42e9-4e2f-ba8b-43e562dd0c07.png">

**Comment by chongbo2013** [comment]
Hello, my map is very big, and the characters are stuck when walking. How should I optimize the map for big maps

**Comment by chongbo2013** [comment]
@RafaelBarbosatec help thank u

**Comment by RafaelBarbosatec** [comment]
> Hello, my map is very big, and the characters are stuck when walking. How should I optimize the map for big maps 

Bonfire already optimizes large maps to the maximum, it only renders and updates visible parts of the map.

If possible divide your map into parts and load it when you enter the area.
Like this example: https://bonfire-engine.github.io/#/examples?id=multi-biome

This give you a better performance.
