### ISSUE TITLE
fix bonfire camera 2.11.11

### ISSUE THREAD

**Issue by pmella16** [RafaelBarbosatec/bonfire#366]
hi after update 2.11.11 the error still happened i modified the _updateLimits method change these lines
#261 

```
      limitMaxX = mapSize.x - (width * zoomFactor);
      limitMaxY = mapSize.y - (height * zoomFactor);

for 

      limitMaxX = mapSize.x + limitMinX - (width * zoomFactor);
      limitMaxY = mapSize.y + limitMinY - (height * zoomFactor);

```
and works fine, but I don't know if it will affect other methods

**Comment by RafaelBarbosatec** [comment]
This way it’s correct. Before was wrong.
It is not necessary to add with the starting position of the map
