### ISSUE TITLE
WorldMapByTiled's objectsBuilder not read Tilsets defined objects 

### ISSUE THREAD

**Issue by fehencke** [RafaelBarbosatec/bonfire#368]
When you use:
`BonfireWidget(
      map: WorldMapByTiled('maps/map_1_export.json',
          objectsBuilder: {
            'wall': (properties) =>
                Wall(position: properties.position, size: properties.size)
          }),
      ),
    )`
The WorldMapByTiled - objectsBuilder search only in Tiled's Map,json Objects (layers[ ].objects)

When you defined the object in Tiled's Tilset.json the Object you cant use WorldMapByTiled - objectsBuilder 
Like that: (tiltset.json)
`{ "columns":2,
 "image":"map_atlas.png",
 "imageheight":32,
 "imagewidth":64,
 "margin":0,
 "name":"map_atlas",
 "spacing":0,
 "tilecount":2,
 "tiledversion":"1.9.2",
 "tileheight":32,
 "tiles":[
        {
         "id":0,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "objects":[
                    {
                     "class":"wallclass",
                     "height":32,
                     "id":2,
                     "name":"wall",
                     "rotation":0,
                     "visible":true,
                     "width":32,
                     "x":0,
                     "y":0
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }],
 "tilewidth":32,
 "type":"tileset",
 "version":"1.9"
}`

(The Tilset's objects automatic added to the game, but you cant use the objectsBuilder and make your own class.)

Thank You, Happy new year!

**Comment by RafaelBarbosatec** [comment]
Hi @fehencke !
Happy new year too! 😊
I didn’t know that it’s possible adds objects in a tileset. Do you can show me how you can do this?
In my Tiled's version is possible only set collision in tileset.

**Comment by fehencke** [comment]
Open the TileSet file - Select a tile - At tile collision editor you can add object.

(I find a other bug also if you add enemy to BonfireWidget and when BonfireWidget.onLoad invoke and try to get all enemies list it return null. I not know its a bug, but how i imagine the onLoad invoke when the BonfireWidget full ready and i can use gameRef.enemies)

**Comment by RafaelBarbosatec** [comment]
So, this is the collision configuration. The areas of collision of the tile. Bonfire already adds this area of collision in the tile.

If you want add objects you need add objects in the map instead of tileset.

**Comment by fehencke** [comment]
Yes it add these objects, but you cant configure simply.  ObjectsBuilder is really good, but if you cant use for all options you will not use.

"If you want add objects you need add objects in the map instead of tileset." This solution is not the best practice. If you build a big map you cant do. Forexample you paint a Door on the map and you want add the object every time? Or you not paint, you just put the object and will paint the app, but that way not see the paint in the Tiled App. So the best if you can add in the Set, because each Door tile will have a Door object.
