### ISSUE TITLE
Fixed map height and width

### ISSUE THREAD

**Issue by griotdonation** [RafaelBarbosatec/bonfire#369]
Hi Rafael,

Is there a way to set a fixed map height and width?

**Comment by RafaelBarbosatec** [comment]
Hi @griotdonation !
The height and width of map is defined by you map created in Tiled. width : Count tiles * tiles width | height : Count tiles * tiles height.

**Comment by griotdonation** [comment]
Ah I see. Ok thanks so much for messaging back!
