### ISSUE TITLE
Turn based bonfire: move 16x16 spaces with 32x32 character

### ISSUE THREAD

**Issue by griotdonation** [RafaelBarbosatec/bonfire#370]
Hi Rafael,

Hope all is well brother. Quick question regarding the turn based example using bonfire, I see the spaces available to move are relative to the player size. Is it possible to have a larger character in size but move smaller spaces. Here an picture for reference ![image](https://user-images.githubusercontent.com/55745803/211235349-8efeb94e-cc5d-46f9-82d0-d43d34e53553.jpeg)

**Comment by RafaelBarbosatec** [comment]
Hi @griotdonation !
Yes, it’s possible! 
In this example the grid area to move is the tile-size, And the movement of the player/enemy is considered the collision area. So, the player or enemy could be anyway size, just keep the collision area eguals or less tile-size.

**Comment by griotdonation** [comment]
awesome! I'll try this! thank, rafael!

**Comment by griotdonation** [comment]
``
