### ISSUE TITLE
Collision from bottom of player

### ISSUE THREAD

**Issue by griotdonation** [RafaelBarbosatec/bonfire#371]
Hi Rafael,

sorry just one more question. is there any easy way in bonfire to check collision from bottom of player?

**Comment by RafaelBarbosatec** [comment]
Hi @griotdonation .
I'm sorry for the late.
Yes it's possible. You can do override in method onCollision and calculate if the collision was do from bottom.
You can calculate this comparing the y axis of center of components.

**Comment by griotdonation** [comment]
@RafaelBarbosatec No worries at all! thank you so much for your response. I'll go ahead and apply your suggestion! thanks again.
