### ISSUE TITLE
Using bonfire for a  platformer - Added gravity but collision is ignored

### ISSUE THREAD

**Issue by beanhead217** [RafaelBarbosatec/bonfire#374]
Hi Rafael,

I hope you are well. I'm hoping you can help with an issue I'm facing. I'm trying my best to use bonfire for a platformer-style game as `opposed` to the RPG style. I've added gravity and a jump function, but for some reason, when gravity is enabled the player falls right through the floor. I expected the collision to stop the fall. The collision seems to work with the roof and side walls.

Here is the repository. I used your "Player Gun Example" repository as a base, and also the jump functionality is behind the Yellow Button. All the additional code has been added to the kelvin.dart file

https://github.com/beanhead217/game_player_gun_example-master-2

Thank you in advance for any feedback or help!

**Comment by rafaelbarbosadrip** [comment]
Hi @beanhead217 !
Bonfire is focused to facilitate in build RPG games. There is not gravity configuration in the moment.
To create platform games I recommend use Flame with Forge2D.

**Comment by beanhead217** [comment]
Thank you so much! Appreciate the response
