### ISSUE TITLE
Event RawKeyUpEvent is never handled

### ISSUE THREAD

**Issue by mel-mouk** [RafaelBarbosatec/bonfire#379]
Hi,
The Joystick never triggers UP event from keyboard. (Bonfire 2.12.0).

After investigation, I noticed that `keysPressed.isEmpty` is always true for `RawKeyUpEvent`.
So in `lib/joystick/joystick.dart` line 160 the condition is true and we never reach the check for RawKeyUpEvent.

My understanding is that this condition is useful to trigger Idle when we stop moving. So I think the fix might be to refactor this to check if we're processing a directional event or an action before checking this.

But as I'm new to Bonfire I think I might lack some context.

I also noticed an issue when pressing multiple keys. I'm trying to run when pressing shift. If I press the directional keys first, it works. But if I press shift first, directional keys appear in keysPressed but is not the one in the event.logicalKeys which break the behavior.

**Comment by RafaelBarbosatec** [comment]
Hi @mel-mouk ! Thanks so much for contacting.
It’s a good point! I'll analyze a way to resolve this.

**Comment by mel-mouk** [comment]
Thanks! Let me know if I can help, I love Bonfire and I plan to build on top of it so I would be happy to contribute if I can

**Comment by raLaaaa** [comment]
> I also noticed an issue when pressing multiple keys. I'm trying to run when pressing shift. If I press the directional keys first, it works. But if I press shift first, directional keys appear in keysPressed but is not the one in the event.logicalKeys which break the behavior.

Can totally confirm this with `left`, `right` and `space`. This is also happening in the online demos.
Are there any news on this or can we contribute somehow?

**Comment by RafaelBarbosatec** [comment]
In the version `2.12.3` i did some improvements! Take a look if it got better!
I hope that this can help you!

**Comment by raLaaaa** [comment]
@RafaelBarbosatec works like a charm for me! 
Thank you for your awesome work.
