### ISSUE TITLE
Any way to update/animate the `lightingColorGame` provided to `BonfireWidget`? 

### ISSUE THREAD

**Issue by sarthak333** [RafaelBarbosatec/bonfire#380]
I want to update the map lighting to reflect the change from day to evening to night without losing the game state. The game controller and gameRef don't seem to have this functionality. Any way I can make this work?

**Comment by pmella16** [comment]
gameref works fine

   gameRef.lighting?.animateToColor(Colors.black.withOpacity(0.9));

**Comment by sarthak333** [comment]
Yeah. Working. Thanks!
