### ISSUE TITLE
Assets error

### ISSUE THREAD

**Issue by GuilhermeHHMS** [RafaelBarbosatec/bonfire#381]
When I increase the code complexity, all assets break for no reason.  All assets worked before I tried to use GestureDetector.

![error n](https://user-images.githubusercontent.com/85815695/223788171-0b38f720-5a6d-4af5-9eef-83c51d4276ab.png)

**Comment by RafaelBarbosatec** [comment]
Hi @GuilhermeHHMS !
I think that not understanding very well your problem. Could you give more information? Code, etc
Why you use `GestureDetector ` and where?

**Comment by GuilhermeHHMS** [comment]
Tem problema eu falar em português?

**Comment by GuilhermeHHMS** [comment]
Bom, sou "iniciante" em Flutter. Eu fiz um código de um GameDecoration, com o GestureDetector. Eu não gosto de usar o chatGPT, mas tive que recorrer a ele para implementar uma lógica. Nessa lógica, eu estava tentando utilizar o mouse para guiar um item. Ele recomendou o GestureDetector e a propriedade de onPanUpdate. Quando inclui o onPanUpdate, todos os meus Assets pararam de funcionar, incluindo o mapa, o player, o item, as imagens de tileset, tudo. Não tenho o código, pois refiz do zero. Deu o mesmo problema 2 vezes. Ambas utilizavam o GestureDetector.

**Comment by GuilhermeHHMS** [comment]
Não tenho absoluta certeza de quando que dá o problema, mas acredito que está relacionado ao GestureDetector.

Outra coisa é a dificuldade para usar um Sprite no GameDecoration, pois na classe que eu criei, tive que criar uma Future para retornar uma imagem através do path.

**Comment by GuilhermeHHMS** [comment]
Caso tenha interesse, a lógica que eu tentei implementar era a de que a espada deveria ficar fixada no player, e a ponta dela deveria acompanhar o cursor do mouse. Tentei com o ChatGPT, mas estava difícil até para ele. Teria como eu fazer isso?  Quero muito criar um jogo com essa mecânica, ai qualquer coisa eu dou uma boa estudada no package, com mais certeza de encontrar uma solução, pois nem sei se tem como.

**Comment by RafaelBarbosatec** [comment]
Oi Guilherme. Então, o ChatGPT não vai te ajudar direito no Bonfire. Rsrsrs 
Não se usa GestureDetector para obter gestures no Bonfire. Consulte a documentação, lá é o melhor caminho:
https://bonfire-engine.github.io/#/gestures

Em relação ao adicionar Sprite ao GameDecoration, não é necessário adicionar um Future como vc comentou.
Recomendo você dar uma olhadinha em alguns tutoriais no YouTube e ou analisar os exemplos disponíveis no próprio site do Bonfire.

https://youtube.com/playlist?list=PLv1_7bM0w6JPkMd3X2FF_TNbDrbChRCV7
