### ISSUE TITLE
dynamic player and joystick action

### ISSUE THREAD

**Issue by kimsean** [RafaelBarbosatec/bonfire#384]
Hi. How can i change dynamically the player and the joystick action on BonfireWidget ?

**Comment by RafaelBarbosatec** [comment]
Hi @kimsean !
You can change the Joystick listener using:

```dart
gameRef.addJoystickObserver(
          NewJoystickListener (component tha implements JoystickListener),
          cleanObservers: true,
          moveCameraToTarget: true,
        );

```

You can get access of Joystick this way:

```dart
    await (gameRef.joystick as Joystick).addAction(JoystickAction());
    await (gameRef.joystick as Joystick).removeAction(JoystickAction);
    await (gameRef.joystick as Joystick).updateDirectional(JoystickDirectional());
```

I hope that this can help you.

**Comment by kimsean** [comment]
Hi @RafaelBarbosatec How about the player ?

**Comment by RafaelBarbosatec** [comment]
`And about this code Where should i add it ? on init state?`

You can run this code when you need change de player in your game. Basically your joystick will control this other component.
 No in `InitState` of the Flutter, you can do it in you game (into any GameComponent).

About change the player, what your case? What do you trying do?
Only add this component in the game and after that give to Joystick the control of this component.

**Comment by kimsean** [comment]
> `And about this code Where should i add it ? on init state?`
> 
> You can run this code when you need change de player in your game. Basically your joystick will control this other component. No in `InitState` of the Flutter, you can do it in you game (into any GameComponent).
> 
> About change the player, what your case? What do you trying do? Only add this component in the game and after that give to Joystick the control of this component.

```
About change the player, what your case? What do you trying do?
```

I have like 3 characters to control, and each character will be controlled per turn.

**Comment by kimsean** [comment]
i got it now.
What i did is this.
```
  @override
  void updateGame() {
    counter = counter + 1;
    if (counter >= 10 && counter <= 20) {
      _controller.gameRef.addJoystickObserver(
        charOne,
        cleanObservers: true,
        moveCameraToTarget: true,
      );
    } else if (counter >= 21) {
       _controller.gameRef.addJoystickObserver(
        charTwo,
        cleanObservers: true,
        moveCameraToTarget: true,
      );
    }
    // TODO: implement updateGame
  }
```

the conditions are just test to check if it actually changes the character to control

**Comment by RafaelBarbosatec** [comment]
> i got it now. What i did is this.
> 
> ```
>   @override
>   void updateGame() {
>     counter = counter + 1;
>     if (counter >= 10 && counter <= 20) {
>       _controller.gameRef.addJoystickObserver(
>         charOne,
>         cleanObservers: true,
>         moveCameraToTarget: true,
>       );
>     } else if (counter >= 21) {
>        _controller.gameRef.addJoystickObserver(
>         charTwo,
>         cleanObservers: true,
>         moveCameraToTarget: true,
>       );
>     }
>     // TODO: implement updateGame
>   }
> ```
> 
> the conditions are just test to check if it actually changes the character to control

It's seems be wrong. Doing it in de update can execute this many times. I think better adds like `joystickObserver` in the own `char` in the `mounted` method.
