### ISSUE TITLE
What is the RouterComponent equal in Bonfire ?

### ISSUE THREAD

**Issue by kimsean** [RafaelBarbosatec/bonfire#386]
Hi. I have 3 screens.

Login
Character Selection screens
Fight Screens

What is the process of navigation in Bonfire?

Should i use the basic Navigator router of Flutter?
I found out that Flame has a RouterComponent.

How can do navigation in Bonfire ?

**Comment by RafaelBarbosatec** [comment]
Hi @kimsean !
I recommend you use Flutter navigator. It's the better and more easy way to build layouts and interface.

So, you can create the Login and Character Select screen in Flutter and only the Fight screen, that would be the game, made in Bonfire.
