### ISSUE TITLE
run issues.

### ISSUE THREAD

**Issue by kimsean** [RafaelBarbosatec/bonfire#389]
Hi. I just created a new project, and i am now getting this issue.

  bonfire: ^2.12.0

I have already tried flutter clean, deleting pubspec.lock, clearing cache. 
but the issue is still there.

![image](https://user-images.githubusercontent.com/20282679/230520617-91f9691b-3531-4316-b67d-3b6fa6b46957.png)

**Comment by RafaelBarbosatec** [comment]
Hi @kimsean !
Thanks for reporting it.
Probably i need update something. The new Version of Flame generated some braking changes

**Comment by RafaelBarbosatec** [comment]
Fix available in version `2.12.1`
