### ISSUE TITLE
game component moveLeft, moveRight stop ?

### ISSUE THREAD

**Issue by kimsean** [RafaelBarbosatec/bonfire#391]
Hi. Is there a function that will execute

moveLeft or moveRight only once?

because if i execute moveLeft, or moveRight It does not stop until it collide something.

Any alternative or suggestions ? thank you

**Comment by RafaelBarbosatec** [comment]
Hi @kimsean !
Where do you are calling the `moveRight` method?
Se you call this method in `update` method really it stop when happen collision. 
You need control it somehow.

Maybe to use [SceneBuilder](https://bonfire-engine.github.io/#/scene_builder) could help you. Or taking a look in the code of this `MoveComponentSceneAction`.

**Comment by kimsean** [comment]
Hi. I want to move remote player via action. I am currently moving it by setting its position according to the values from socket.

The problem is that, it is not smooth and it does not render the sprite facing direction.

I know there were examples on github. But i am confused on it.

What are your tips on moving a component via position values only ?, The movement is joystick and not the auto path.

**Comment by RafaelBarbosatec** [comment]
You need send from the socket the moment what you want stop de moment.
I have a example for this in this project:
https://github.com/RafaelBarbosatec/mountain_fight

Unfortunately the backend is stoped in the moment.

**Comment by kimsean** [comment]
to move other players around.

What is the best solution?
Should i set the position of other players by the position sent by backend?
or move the player according the function moveLeft, moveRight etc. ?

@RafaelBarbosatec

**Comment by RafaelBarbosatec** [comment]
> to move other players around.
> 
> What is the best solution?
> Should i set the position of other players by the position sent by backend?
> or move the player according the function moveLeft, moveRight etc. ?
> 
> @RafaelBarbosatec 

Só, depends of the type of game.
If the movement in your game is by click to position is good you send the position, if not, only update the state (move left, move right, idle, etc)

**Comment by kimsean** [comment]
@RafaelBarbosatec 

> If the movement in your game is by click to position is good you send the position

In this section, how can i get the event tap on the map? Because on tap in map tile, i want to move the character via auto path.
