### ISSUE TITLE
How to identify if there is a collisionObject between two point (player and enemy)

### ISSUE THREAD

**Issue by griotdonation** [RafaelBarbosatec/bonfire#395]
Hi Rafael!

Hope all is well. id there an existing function bonfire to know if there is objectCollision between the distance of the player and enemy? For example, if im shooting the enemy, but a barrel is in the way, i want to stop shooting.

**Comment by RafaelBarbosatec** [comment]
Hi @griotdonation !
I'm fine! 😊 How about you?

So, you have trying adds collision in your shot bullet?
I normally do this and it's work very well.

**Comment by griotdonation** [comment]
Im well thanks! awesome! cant wait fro the update!!!
