### ISSUE TITLE
Bug in _calculateGridCanAttack & _calculateGridCanMove

### ISSUE THREAD

**Issue by griotdonation** [RafaelBarbosatec/bonfire#396]
Hi Rafael,

Sorry to bother, I just see a bug i was hoping you can help solve. This regarding the "TurnGame" logic where you have code to calculate gridCanMove and gridCanAttack. Essentially we remove positions to move where the is an object collision. See code below. the issue is when the player is facing left (isFlipHorizontally), the code appears to remove the opposite position. Any help will be very much appreciated.

` 
void _calculateGridCanAttack() {
    countTileRadiusAttack = Vector2.all(3);
    _gridCanAttack.clear();
    double xGrid = rectYourGridPosition.left;
    double yGrid = rectYourGridPosition.top;

    double displacementX = countTileRadiusAttack.x * DungeonMap.tileSize ;
    double displacementY = countTileRadiusAttack.y * DungeonMap.tileSize;

    double startXGrid = xGrid - displacementX;
    double startYGrid = yGrid - displacementY;

    int sizeX = countTileRadiusAttack.x.toInt() * 2 + 1;
    int sizeY = countTileRadiusAttack.y.toInt() * 2 + 1;

      List.generate(sizeY, (indexY) {
        List.generate(
          sizeX,
              (indexX) {
            var rect = Rect.fromLTWH(
              startXGrid + indexX * width,
              startYGrid + indexY * height,
              width,
              height,

            );

            bool containCollision = gameRef.collisions().where((element) {
              // return element.rectConsideringCollision.overlaps(rect);
              return element.rectCollision.overlaps(rect);
            }).isNotEmpty;

            if (!containCollision) {
              _gridCanAttack.add(rect);
            }
          },
        );
      });
  }

`

![Apr-20-2023 19-10-17](https://user-images.githubusercontent.com/55745803/233506098-73f857e7-87f4-4482-af3a-21ae48043dd6.gif)

**Comment by RafaelBarbosatec** [comment]
HI @griotdonation !
I'm sorry for late.
It's right, the paint was invented because when you turn your player to left the canvas do flip horizontally.
Try move render of this red area to `renderBeforeTransformation`

**Comment by griotdonation** [comment]
No worries! I just appreciate your response! I'll give this a shot. Thanks Rafael!
