### ISSUE TITLE
Ignore Collision for simpleAttackRangeByAngle

### ISSUE THREAD

**Issue by beanhead217** [RafaelBarbosatec/bonfire#398]
Is there a way to ignore collision for specific game components for the simpleAttackRangeByAngle function? I do not want the bullets to collide with friendly NPC that follows.

**Comment by RafaelBarbosatec** [comment]
Hi @beanhead217 !
Thanks for this issue. In the version `2.12.3` you can do override in `onCollision` like this:
```dart
@override
  bool onCollision(GameComponent component, bool active) {
    if (component is FlyingAttackObject) {
      return false;
    }
    return super.onCollision(component, active);
  }
```

**Comment by beanhead217** [comment]
Thanks Rafael! I gave a shot and it worked! I do see, for some reason, when the critter NPC is NOT moving the bullets don't collide. But when the critters is actively moving the bullets do collide, even with override. 

Any idea why this maybe?

**Comment by beanhead217** [comment]
I'll try to troubleshoot if this isn't a known issue. Thanks so much!
