### ISSUE TITLE
Flutter Web does not support the blend mode: BlendMode.clear

### ISSUE THREAD

**Issue by PonthepYJ** [RafaelBarbosatec/bonfire#40]
I have got this error when trying to run on web.The first screen shown up but after click on Manual Map or Tiled Map then the error "Flutter Web does not support the blend mode: BlendMode.clear" display in flutter console. and following by non stop throwing "PersistedScene: is in an unexpected state." error message.

**Comment by RafaelBarbosatec** [comment]
The Flame engine that is used in this package only works in release mode and with better performance with SKIA enabled. So I recommend you to run like this: 
`flutter run -d chrome --release --dart-define = FLUTTER_WEB_USE_SKIA = true`

But yes, it is not entirely stable on the WEB. out of nowhere it crashes. We are looking at what may be causing this together with the Flame team. And if necessary we will open an issue for the Flutter team.

Our example running on the web: http://rafaelbarbosatec.github.io/bonfire/#/

**Comment by RafaelBarbosatec** [comment]
If you don't want to use BlendMode.clear. just do not activate the lighting system by not passing the parameter: `lightingColorGame`

**Comment by PonthepYJ** [comment]
Thanks for your quick answer.I really appreciate what you have done on this project.

**Comment by PonthepYJ** [comment]
> The Flame engine that is used in this package only works in release mode and with better performance with SKIA enabled. So I recommend you to run like this:
> `flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true`
> 
> But yes, it is not entirely stable on the WEB. out of nowhere it crashes. We are looking at what may be causing this together with the Flame team. And if necessary we will open an issue for the Flutter team.
> 
> Our example running on the web: http://rafaelbarbosatec.github.io/bonfire/#/

After I try running in profile mode I found that the game will crash within 5 minutes with error " CanvasKit threw an exception while laying out the paragraph. The font was "Arial". Exception:".

I googled and found that canvaskit wasm has some bug about releasing memory when using paragraph from this link https://github.com/flutter/flutter/issues/56938

I try working around by comment code on all "_textConfig.render" to not show text on Barrel and Chest in the game and the crash is gone from web running even it had run more than 10 minutes.

May be it is related, and I just would like to share this for your information.

**Comment by parkoriann** [comment]
> The Flame engine that is used in this package only works in release mode and with better performance with SKIA enabled. So I recommend you to run like this: `flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true`
> 
> But yes, it is not entirely stable on the WEB. out of nowhere it crashes. We are looking at what may be causing this together with the Flame team. And if necessary we will open an issue for the Flutter team.
> 
> Our example running on the web: http://rafaelbarbosatec.github.io/bonfire/#/

I had the same problem and fixed this by adding this line to the running arguments, but after I deployed the website and tried to access it from a mobile device, it crashes. So for me, the problem was only solved for development. Is there a special way to build the project when using this blend mode?

**Comment by iCarlosAugusto** [comment]
**Try to use:** 

flutter build web --web-renderer canvaskit

flutter run -d chrome --web-renderer canvaskit
