### ISSUE TITLE
Limiting player moviments from Joystick 

### ISSUE THREAD

**Issue by ericferreira1992** [RafaelBarbosatec/bonfire#401]
Is there a way to limit moviments? My game is 45 perspective, and I need just left and right moviments, also jump on boxes. How I can joystick prevent other commands?

**Comment by RafaelBarbosatec** [comment]
Hi @ericferreira1992 !
In your Player you can do override `joystickChangeDirectional` and call `super` only the directions accepted

**Comment by ericferreira1992** [comment]
Cool, I achieved! Thanks!
Talking about Player, how I can make he execute a jump Sprite and execute a jump effect too? (ofcourse I will create an action for it)

**Comment by RafaelBarbosatec** [comment]
So, the Bonfire is not indicated to do platform games. although possible. To do the jump you can apply acceleration using the mixin [acceleration](https://bonfire-engine.github.io/#/mixins?id=acceleration).
