### ISSUE TITLE
Bug: onCollision not return false when target is moving

### ISSUE THREAD

**Issue by beanhead217** [RafaelBarbosatec/bonfire#402]
`@override
  bool onCollision(GameComponent component, bool active) {
    if (component is FlyingAttackObject) {
      return false;
    }
    return super.onCollision(component, active);
  }`

I used the above code to ignore collision for simpleAttackRangeByAngle. But I find that when the target is moving the component still collides with the target object.

![Apr-27-2023 09-04-55](https://user-images.githubusercontent.com/112144591/234871333-dd7cfbe3-6424-404a-b2b8-6ec6f4ace640.gif)

**Comment by RafaelBarbosatec** [comment]
Hi @beanhead217 !
Please check the version `2.12.4`

**Comment by beanhead217** [comment]
Version 2.12.4 works perfectly!! You rock! thanks, Rafael!
