### ISSUE TITLE
On mobile if I use joystick suddenly all UI elements vanish (no exception)

### ISSUE THREAD

**Issue by raLaaaa** [RafaelBarbosatec/bonfire#408]
Hey, this one is really odd:

If I run the game on mobile (doesnt matter emulator or physical) and choose joystick suddenly all UI elements vanish (lightning, healthbar etc.) everything else is working as expected. This does only happen when I start moving by using the controller (if I just stand still nothing happens). No exception is popping up. I'm basically using a slighty modified version of: https://github.com/RafaelBarbosatec/darkness_dungeon

Using the controller in the web version works. What confuses me is that there is no exception coming up. I think console logs are fine too. Could you give me a hint how I could debug this?

**Comment by KyleKun** [comment]
Hi @raLaaaa , if you can upload your project or a minimal reproducible code on a new repo, I think it will be easier to help.

**Comment by raLaaaa** [comment]
@KyleKun - you are right. I was just wondering whether there is any known behavior where no exception is popping up and the entire UI is vanishing. The example project can be found here:

https://github.com/raLaaaa/crystal-game

I can not provide a minimal reproducible code unfortunately since I'm really not sure when this happens. 
This happens for me on a Pixel 5 with API 32 physically and on an emulator.

**Comment by raLaaaa** [comment]
Thank you for looking into it. Is it solved with the newest version? 👍 Or is the issue on my side?

**Comment by RafaelBarbosatec** [comment]
I’m sorry for close this issue.
I'm not mighty reproduce this issue yet.
You can share at least a screenshot?

**Comment by raLaaaa** [comment]
I'm on vacation right now. I'll do a video on Monday. Interesting to hear that you can not reproduce it with https://github.com/raLaaaa/crystal-game .

Thank you!

**Comment by raLaaaa** [comment]
I uploaded a shirt clip below.
As soon as I start to move all UI / Lightning elements just vanish.

https://github.com/RafaelBarbosatec/bonfire/assets/12799722/ac334ad3-b31c-4412-a341-a0f793bc2d95

**Comment by RafaelBarbosatec** [comment]
Humm, this happen when occurs some error in the game (some crash in the game loop). I will download this project and try find out this error.
It must be some very specific point in this project

**Comment by RafaelBarbosatec** [comment]
I found!
Something wrong in the Flame component `FpsTextComponent`
Just comment this code in `KnightInterface` like that:

![image](https://github.com/RafaelBarbosatec/bonfire/assets/10039275/6852fa1e-1ed1-4b3c-adee-2ac0b2f0c589)

And your project works fine

**Comment by raLaaaa** [comment]
This indeed fixes it! 
Thank you so much.

Is the `FpsTextComponent` flawed or did I use it incorrectly?

**Comment by raLaaaa** [comment]
I'll fix it for now - in case this is an error inside the library feel free to reopen @RafaelBarbosatec .
Thank you!
