### ISSUE TITLE
Need help to support different size of sprite sheet 

### ISSUE THREAD

**Issue by leonlee0116** [RafaelBarbosatec/bonfire#409]
Hi!
I have 2 different sprite size.

static final normalSpriteSize = Vector2.all(64);
static final largeSpriteSize = Vector2.all(192);

normalSpriteSize for walking and idle sprite animation
![image](https://github.com/RafaelBarbosatec/bonfire/assets/47915700/35618ef9-f310-4e1f-a7d4-3e4fd5df0100)

largeSpriteSize was used for attack sprite animation
![image](https://github.com/RafaelBarbosatec/bonfire/assets/47915700/d2c1886f-155a-48a0-b695-09717ca45a63)

But i have issues when play attack animation as shown in the video below
https://github.com/RafaelBarbosatec/bonfire/assets/47915700/16930e11-ccd6-4444-b0e1-ed119288b3da

I think I do something wrong, please help me :(

**Comment by KyleKun** [comment]
Hi @leonlee0116 , doesn't changing the textureSize solves the problem? Can you share the code where the spritesheet is declared and loaded?

**Comment by RafaelBarbosatec** [comment]
Hi @leonlee0116 !
Your sprite animation of attack is bigger than movements sprite. So, you can set the size and offset when you call `animation?.playOnce`:

```dart
animation?.playOnce(MyAttackAnimation,size: Vector2(newWidth, newHeight));
```
Try use this to play your animation attack in the same proportion of the other animations.
