### ISSUE TITLE
Allow to use Bonfire classes without need to wrap with BonfireWidget

### ISSUE THREAD

**Issue by d-apps** [RafaelBarbosatec/bonfire#41]
I'm building a game but is not an RPG and your widgets could be very helpful, could you please see if it's possible to allow to use your classes (Joystick, Interface, Lighting, Enemy and Camera) without need to wrap the app inside BonfireWidget, so I can just render as Components and custom their actions?

For example, If I try to render a Joystick I get **size = null**, since I didn't use BonfireWidget, but if I use it I don't have a map since it's not an RPG game and the parameter **map** is required.

import 'dart:ui';
import 'package:bonfire/bonfire.dart';
import 'package:flame/components/component.dart';

```
class CustomJoystick extends Component {

  Joystick joystick;

  CustomJoystick(){

    joystick = Joystick(
      actions: [



      ]
    );

  }

  @override
  void render(Canvas c) {
    joystick.render(c);

  }

  @override
  void update(double dt) {
    joystick.update(dt);
  }

  
}
```

```
class AlienGame extends BaseGame with PanDetector, HasGameRef {

  AlienGame(Size screenSize){

    this.size = screenSize;

    add(Background());

    add(PlayerComponent());

    add(CustomJoystick());
```

```
 The following NoSuchMethodError was thrown during a scheduler callback:
I/flutter (32538): The getter 'size' was called on null.
I/flutter (32538): Receiver: null
I/flutter (32538): Tried calling: size
I/flutter (32538): When the exception was thrown, this was the stack:
I/flutter (32538): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
I/flutter (32538): #1      Joystick.update (package:bonfire/joystick/joystick.dart:44:17)
I/flutter (32538): #2      CustomJoystick.update (package:aliengame/src/components/joystick.dart:30:14)
```

**Comment by RafaelBarbosatec** [comment]
Unfortunately it will not be possible to use this component outside the Bonfire framework, it depends on a proper implementation of BaseGame. But I'm working with the Flame team to add this feature to their package.
