### ISSUE TITLE
Possibility to add the GameComponent spawner in V3.0.0

### ISSUE THREAD

**Issue by UR4N0-235** [RafaelBarbosatec/bonfire#414]
I miss a some GameComponent to create RPG games like of [The Legend of Zelda](https://en.wikipedia.org/wiki/The_Legend_of_Zelda), where in certain places a certain enemy could be a spawn from time to time, not only once. At the moment I need to make a "technical adjustment" to make this work, but I hope something like this can be implemented in bonfire to create a simple way to generate spawn points around the map.

**Comment by RafaelBarbosatec** [comment]
Hi @UR4N0-235. It's a good idea!
If you have any solution about this, could you open a PR to v3.0.0?

**Comment by RafaelBarbosatec** [comment]
`ComponentSpawner` available in `3.0.0-beta.2`
