### ISSUE TITLE
[question]: How to reset the Manual Map scene of Example

### ISSUE THREAD

**Issue by shinriyo** [RafaelBarbosatec/bonfire#427]
### How can we help?

When the player killed, how to reset the game?
<img width="1040" alt="Screenshot 2023-09-19 at 9 47 23" src="https://github.com/RafaelBarbosatec/bonfire/assets/396927/7903f729-83ee-4682-a229-96717f7d4a05">

Just back and go back again?
No reset button?

**Comment by shinriyo** [comment]
It's also concerning that the gauge remains when the player dies.

**Comment by RafaelBarbosatec** [comment]
Yes. I don't put the reset button in this example. ☺️
There are others examples that have reset button. 

https://bonfire-engine.github.io/#/examples?id=sunnyplace-in-development

**Comment by RafaelBarbosatec** [comment]
I will do improvements in this examples in the version 3.0.0
