### ISSUE TITLE
[Bug]: There's something wrong with the tile joints

### ISSUE THREAD

**Issue by shinriyo** [RafaelBarbosatec/bonfire#429]
### What happened?

There's something wrong with the tile joints

<img width="1084" alt="Screenshot 2023-09-19 at 11 28 15" src="https://github.com/RafaelBarbosatec/bonfire/assets/396927/868e2813-93fe-4b92-a74a-adcc05eb99f0">

### Steps to reproduce?

```Markdown
1. go to Random Map


1. go to Multi Scenario
```

### What did you expect to happen?

beautiful tile joints

### Bonfire version

v2.11.5

**Comment by shinriyo** [comment]
<img width="855" alt="Screenshot 2023-09-19 at 11 47 48" src="https://github.com/RafaelBarbosatec/bonfire/assets/396927/43f3450b-a132-4337-a688-1d98e5b82d09">

However, README's animation are beautiful.

**Comment by RafaelBarbosatec** [comment]
There must be a problem running on IOS. In other platforms its not happen.
I will try analysis this.

![image](https://github.com/RafaelBarbosatec/bonfire/assets/10039275/c45d8533-2d30-475c-a6f6-4b52e17f0e01)

**Comment by shinriyo** [comment]
Is it on Android?

**Comment by RafaelBarbosatec** [comment]
Please test using the branch 3.0.0.
It's the next release. I'm not working in the version 2.0

**Comment by shinriyo** [comment]
Ok

**Comment by shinriyo** [comment]
I tried it on `v3.0.0`.

Same happened.

<img width="1080" alt="Screenshot 2023-09-20 at 9 29 37" src="https://github.com/RafaelBarbosatec/bonfire/assets/396927/3ec470e5-06d5-4e37-94c7-e5ff5bcb09e8">

**Comment by RafaelBarbosatec** [comment]
Something wrong with Impeller rendering.
Wait for Flutter Impeller improvements
