### ISSUE TITLE
[question]: Are there any restrictions on moving the barrel?

### ISSUE THREAD

**Issue by shinriyo** [RafaelBarbosatec/bonfire#431]
### How can we help?

Are there any restrictions on moving the barrel?

<img width="1080" alt="Screenshot 2023-09-21 at 8 35 05" src="https://github.com/RafaelBarbosatec/bonfire/assets/396927/9356229a-b44b-4624-ad75-4cecce464ea1">
I've drawn a line in red for reference, but you can't drag from here onward.

**Comment by RafaelBarbosatec** [comment]
Hi @shinriyo !
No, there is not restrictions. It's a bug and i already find where the problem to fix. It wil be available in next version.
Thanks for report it.

**Comment by shinriyo** [comment]
@RafaelBarbosatec Thank you.
Is it the bug of bonfire or just Examples?

**Comment by RafaelBarbosatec** [comment]
Bonfire bug.
A wrong collision configuration

**Comment by RafaelBarbosatec** [comment]
Fixed in the version beta-15

**Comment by shinriyo** [comment]
Thank you for fix.
