### ISSUE TITLE
[Bug]: The goblin attacks while in conversation

### ISSUE THREAD

**Issue by shinriyo** [RafaelBarbosatec/bonfire#432]
### What happened?

It is funny but the goblin attacks while in conversation.
<img width="1080" alt="Screenshot 2023-09-20 at 15 18 26" src="https://github.com/RafaelBarbosatec/bonfire/assets/396927/ce7db131-de5e-4f59-aba3-012d5e726a73">

### Steps to reproduce?

```Markdown
1. Go to Manual Map.
2. Talk to goblin
```

### What did you expect to happen?

It might be by design, but the knight gets killed during the conversation.
In typical RPG game design, enemies don't get attacked during conversations.

### Bonfire version

v3.0.0-beta.10

**Comment by RafaelBarbosatec** [comment]
It's not a bug, I just not was implement this.
I could do pause in the game using `gameRef.pauseEngine()` or create a global variable to stop all beheavors

**Comment by RafaelBarbosatec** [comment]
You are running in IOS device. From your prints it looks like it's not looking good on this platform.
I'll take some time later to look better at the iPhone. Running on macos everything is OK.

**Comment by shinriyo** [comment]
![ezgif-3-5b660f42eb](https://github.com/RafaelBarbosatec/bonfire/assets/396927/4002d62b-9150-40d7-9d75-3afbfbdbe0dd)

> From your prints it looks like it's not looking good on this platform.
yes it is

**Comment by RafaelBarbosatec** [comment]
It's problem of the Impeller. I found the issue about it in flutter repository. take a look https://github.com/flutter/flutter/issues/132849

**Comment by RafaelBarbosatec** [comment]
To you get a better experience pls test the project in Android device, web using canvaskit or desktop(macos in your case)

**Comment by shinriyo** [comment]
Impeller is a new rendering engine that brought in 3.7.
I tried to use Flutter `3.3.8`, but it uses version Dart `2.18.4` which not be supported by bonfire.

I just will set.

```
// lightingColorGame: Colors.black.withOpacity(0.75),
```
in the file
`example/lib/manual_map/game_manual_map.dart`

**Comment by RafaelBarbosatec** [comment]
Yes, commenting this line your are disabling the lighting system.

**Comment by pmina04** [comment]
To disable Impeller on iOS when deploying your app, add the following tags under the top-level <dict> tag in your app's Info.plist file.

  <key>FLTEnableImpeller</key>
  <false />

**Comment by pmella16** [comment]
To disable Impeller on iOS when deploying your app, add the following tags under the top-level <dict> tag in your app's Info.plist file.

```
  <key>FLTEnableImpeller</key>
  <false />
```
