### ISSUE TITLE
Tile with (price of movement)

### ISSUE THREAD

**Issue by Sproute777** [RafaelBarbosatec/bonfire#438]
Can be implemented Tile with weigh of movement

  if I want to create game with movement through many types of ground (water, sands, mud) , change speed when tiles is other;
  
  
  On start game perhaps gets tiles from Json and parsing manually
  but
  if Map is BIG
       finding path or moves area for unit maybe high cost
       
 other way 
    If  I will be gets a part of map , this is good optimization
    
    
 ```dart
    
    final unit = gameRef.query<Unit>().first;
    final unitPos = _getUnitPos(unit, tileSize);
    final tiles = gameRef.map.tiles;
    
    final squareTiles = tiles.where((tile) => 
             (unitPos.x - tyle.x).abs() + (unitPos.y - tile.y).abs()) < 40 ); // only Square 20 x 20
    print( squareTile.first.weigh); // price or cost
        
    
 ```

**Comment by RafaelBarbosatec** [comment]
HI @Sproute777 !
You can get all tile class that is used to create a Tile when it is visible. This way:
`gameRef.map.tiles` or only visible use ` gameRef.map.getRendered()`

In this class you can get a type (`class` in Tiled) and all properties listed in the tiled.
![image](https://github.com/RafaelBarbosatec/bonfire/assets/10039275/a9080762-6b90-4646-bd31-f124f7c183e8)

Maybe it help you to identify tile types.

To do your component identify what tile is in your below you can use the mixin `TileRecognizer`. There are several functions that help you capture the properties of the tile below it.
