### ISSUE TITLE
[question]: Does the player move for movement on a per-cell basis in the map?

### ISSUE THREAD

**Issue by shinriyo** [RafaelBarbosatec/bonfire#443]
### How can we help?

It is similar to [question]: Does the Pushable class have options for movement on a per-cell basis in the map? #442

<img width="504" alt="Screenshot 2023-10-07 at 16 28 41" src="https://github.com/RafaelBarbosatec/bonfire/assets/396927/54641e4c-b874-4335-91cf-fed8352af5c5">

**Comment by RafaelBarbosatec** [comment]
The player contains a mixin named `Movement`. Probably you will need do override some methods this like `moveLeft`, 'moveRight', 'moveDown' and `moveUp` to do this custom movement

**Comment by KyleKun** [comment]
Also, take a look at the `PathFinding` example from v3.0 (available in develop branch), might be what you're looking for.

**Comment by shinriyo** [comment]
@KyleKun 
<img width="1080" alt="Screenshot 2023-10-09 at 0 16 07" src="https://github.com/RafaelBarbosatec/bonfire/assets/396927/864c93f6-4ae8-41a3-8aba-26325ca9fc42">
OK! Thank you for replying. I will try

**Comment by shinriyo** [comment]
Which is the latest between the `develop` and `v3.0.0` branches?

**Comment by KyleKun** [comment]
> Which is the latest between the `develop` and `v3.0.0` branches?

It is `develop`.

**Comment by RafaelBarbosatec** [comment]
To do it you can also do override the `onJoystickDirectional` to listen the directional joystick interaction and call the method `moveToPosition` to move player to position you want,

**Comment by RafaelBarbosatec** [comment]
You can use the mixin `MovePerCell` in your player
