### ISSUE TITLE
[question]: How to add pulling object option?

### ISSUE THREAD

**Issue by shinriyo** [RafaelBarbosatec/bonfire#445]
### How can we help?

I want to pull the object like this.

![1](https://github.com/RafaelBarbosatec/bonfire/assets/396927/c6543dbc-047b-467c-9778-243711f744de)
↓
![2](https://github.com/RafaelBarbosatec/bonfire/assets/396927/65738102-5097-43f7-b29f-1240ae0b83d2)

**Comment by RafaelBarbosatec** [comment]
Hi @shinriyo .
So, in this case you need implement this behavior. I don’t know, maybe a flag that when enabled the nearby component follow you position.
