### ISSUE TITLE
[question]: By pressing the "▶️" key, the player will no longer continue to move to the right after moving a certain distance.

### ISSUE THREAD

**Issue by kjxbyz** [RafaelBarbosatec/bonfire#451]
### How can we help?

By pressing the "▶️" key, the player will no longer continue to move to the right after moving a certain distance.

[demo](https://www.chenyifaer.com/fafa-runner/play/)

**Comment by RafaelBarbosatec** [comment]
Hi @kjxbyz !
Strange, seems be some collision over there. try init the person little above that position.
After that It doesn't seem to happen anymore during the game
