### ISSUE TITLE
[question]: Get Layer or Group Layer

### ISSUE THREAD

**Issue by MikaReesu** [RafaelBarbosatec/bonfire#452]
### How can we help?

Hello, 

I would like to know if there is a way to get a layer or a group layer with Bonfire? I would like to apply opacity in the code since from Tiled, I have an issue where I can see the tiles grid when opacity is on. I don't know if it's a normal behaviour or a bug. 

Thank you for your answer :)

**Comment by RafaelBarbosatec** [comment]
Hi @MikaReesu !
No you can’t get de layer or a group layer. You can get the tiles visible in the moment using: `var List<Tile> visiblesTile = gameRef.map.getRendered()`, and then to can acesses all properties configurated in Tiled like this `tile.properties` or your class `tile.tileClass`.
So, you can find the tile that you want apply opacity and do it:

```dart
gameRef.map
          .getRendered()
          .where((element) => element.tileClass == 'MySpacialTile')
          .forEach((element) {
        element.opacity = 0.5;
      });
```

In the moment if you do it, all tiles will apply opacity because now all tiles share da same Paint. I will remove this in the next version.

**Comment by MikaReesu** [comment]
Is it bad to do this in terms of performance? 

Thank you for your answer!

**Comment by RafaelBarbosatec** [comment]
So, if you do it in certain moment is not bad. But if you do it 60 times per second, yes its really bad.

**Comment by RafaelBarbosatec** [comment]
Fix available in version 3.0.3

**Comment by MikaReesu** [comment]
What about if I do something like creating a rectangle as an Object in Tiled, the size will be big and after I create a DecorationComponent let's say, I add it to object builder in the WorldMapByTiled and I load a water shader in it. 

Would this be bad in terms of performance?

Thank you for the fix :)

**Comment by RafaelBarbosatec** [comment]
It's a good idea. Anything that more complex in the map should be add in the map this way.
About shaders, it's a subject that I not didn't have touch yet. I think that will stay great. Try it and tell me how goes.

**Comment by MikaReesu** [comment]
I'm gonna try today normally, so I will give you a feedback about that.

Thank you for your feedback!

**Comment by MikaReesu** [comment]
Thank you I just did it, even though it will be better and more accurate to do it with a layer. 
For **Tiled**, I created an **Object** with a **rectangle** zone.

Here is the **code** : 
`Water': (p) => Water(p.position, p.size),`

```
class Water extends GameDecoration {
  Water(Vector2 position, Vector2 size)
      : super(
          position: position,
          size: size,
        );

  @override
  Future<void> onLoad() {
    loadWaterAnimation();
    return super.onLoad();
  }

  void loadWaterAnimation() async {
    final waterTexture = await Sprite.load('textures/water.png');

    final fragmentProgram =
        await FragmentProgram.fromAsset('shaders/water_shader.frag');
    final shader = fragmentProgram.fragmentShader();

    await add(
      WaterComponent(
        sprite: waterTexture,
        shader: shader,
        speed: 10,
        size: size,
        priority: -10,
      ),
    );
  }
}
```

Depending on what you do, I think that inserting a polygon could be more precise.

Also, one thing to notice is that, it is above anything from your map. If you've designed an island and you put the rectangle on it, it's gonna be on top of the island.

**Comment by RafaelBarbosatec** [comment]
You can use the Bonfire priorities LayerPriority.MAP +1 or -1 to render below

**Comment by MikaReesu** [comment]
I didn't know about that. I tried but I apparently I can't reassign a value to it.
It seems to be a const, so I can't modify it outside of his class.

**Comment by RafaelBarbosatec** [comment]
You not would change the class `LayerPriority`. You can set the priority with base this const.

```dart
 await add(
      WaterComponent(
        sprite: waterTexture,
        shader: shader,
        speed: 10,
        size: size,
        priority: LayerPriority.MAP +1,
      ),
    );
``` 

it's will render above only map.

You can also do override of `priority` param in your component fixing a specific priority:

```dart

 @override
  int get priority {
    return LayerPriority.MAP +1;
  }

```

**Comment by RafaelBarbosatec** [comment]
You can share this shader? ☺️ I would like try use it too.

**Comment by MikaReesu** [comment]
Hello, Thank you. 

Do you have any example of using the Layerpriority.map or background? Like in which cases?

Thank you :)

**Comment by MikaReesu** [comment]
For the shaders : 

1. Put this in the pubspec : 

`  shaders:
    - shaders/water_shader.frag`
    
    2. Create a folder shaders at the same level as assets
3. Create a new file water_shader.frag in the shaders folder
4.  Add this code in the file : 

```
#version 460 core

#include <flutter/runtime_effect.glsl>

uniform sampler2D texture0;
uniform vec2 resolution;
uniform float time;
uniform float speed;

out vec4 fragColor;

void main() {
    float x = FlutterFragCoord().x + time * speed;
    float y = FlutterFragCoord().y + time * speed;

    // Sample the texture
    vec2 uv = vec2(x, y) / resolution;
    uv.x = uv.x - int(uv.x);
    uv.y = uv.y - int(uv.y);
    vec4 texColor = texture(texture0, uv);
    fragColor = texColor;
}
```
5. Create a new component called WaterComponent(put it where you want)

```
import 'dart:ui';
import 'package:bonfire/bonfire.dart';

class WaterComponent extends SpriteComponent {
  WaterComponent({
    required super.sprite,
    required this.shader,
    required this.speed,
    super.size,
    super.priority,
  });

  final FragmentShader shader;
  double _timeElapsed = 0.0;
  final double speed;

  @override
  Future<void> onLoad() async {
    // Set the texture
    shader.setImageSampler(0, sprite!.image);

    // Set the resolution
    shader.setFloat(0, sprite!.originalSize.x);
    shader.setFloat(1, sprite!.originalSize.y);

    // Set the speed
    shader.setFloat(3, speed);

    paint.shader = shader;
  }

  @override
  void update(double dt) {
    _timeElapsed += dt;
    shader.setFloat(2, _timeElapsed);
  }

  @override
  void render(Canvas canvas) {
    canvas.drawRect(Rect.fromLTWH(x, y, size.x, size.y), paint);
  }
}

```

6. Add the class Water which is a GameDecoration : 
```
class Water extends GameDecoration {
  Water(Vector2 position, Vector2 size)
      : super(
          position: position,
          size: size,
        );

  @override
  Future<void> onLoad() {
    loadWaterAnimation();
    return super.onLoad();
  }

  void loadWaterAnimation() async {
    final waterTexture = await Sprite.load('textures/water.png');

    final fragmentProgram =
        await FragmentProgram.fromAsset('shaders/water_shader.frag');
    final shader = fragmentProgram.fragmentShader();

    await add(
      WaterComponent(
        sprite: waterTexture,
        shader: shader,
        speed: 10,
        size: size,
        priority: -10,
      ),
    );
  }
}
```

7. In tiled, create a new object, add a rectangle and assign the name water and after you just have to add it in the object builder.

8. Find a water texture, you can easily find some online, or in case send me a message in discord and I will share some with you to test. 

Tell me if you have any questions but it should work :)

**Comment by RafaelBarbosatec** [comment]
Really nice! ❤️

https://github.com/RafaelBarbosatec/bonfire/assets/10039275/ae1d8679-4112-4632-8ac6-dae81bed3264

![image](https://github.com/RafaelBarbosatec/bonfire/assets/10039275/a842f656-4cda-4afa-be68-de8f8b07027e)


```dart
return Scaffold(
      body: BonfireWidget(
        joystick: Joystick(directional: JoystickDirectional()),
        map: WorldMapByTiled(
          'map.tmj',
          objectsBuilder: {
            'water': (prop) => WaterComponent(
                  position: prop.position,
                  size: prop.size,
                  speed: 5,
                )
          },
        ),
        cameraConfig: CameraConfig(
          zoom: 2,
        ),
      ),
    );
```

```dart
class WaterComponent extends GameComponent {
  WaterComponent({
    required this.speed,
    required Vector2 position,
    required Vector2 size,
  }) {
    this.position = position;
    this.size = size;
  }

  late Sprite sprite;
  late FragmentShader shader;
  double _timeElapsed = 0.0;
  final double speed;

  @override
  Future<void> onLoad() async {
    final sprite = await Sprite.load('water.png');

    final fragmentProgram = await FragmentProgram.fromAsset(
      'shaders/water_shader.frag',
    );
    shader = fragmentProgram.fragmentShader();
    // Set the texture
    shader.setImageSampler(0, sprite.image);

    // Set the resolution
    shader.setFloat(0, sprite.originalSize.x);
    shader.setFloat(1, sprite.originalSize.y);

    // Set the speed
    shader.setFloat(3, speed);

    paint.shader = shader;
  }

  @override
  void update(double dt) {
    super.update(dt);
    _timeElapsed += dt;
    shader.setFloat(2, _timeElapsed);
  }

  @override
  void render(Canvas canvas) {
    canvas.drawRect(Rect.fromLTWH(x, y, size.x, size.y), paint);
  }

  @override
  int get priority => LayerPriority.BACKGROUND;
}
```

**Comment by RafaelBarbosatec** [comment]
Or 

```dart

return Scaffold(
      body: BonfireWidget(
        joystick: Joystick(directional: JoystickDirectional()),
        map: WorldMapByTiled('map.tmj'),
        components: [
          WaterBackground(
            speed: 5,
          )
        ],
        cameraConfig: CameraConfig(
          zoom: 2,
        ),
      ),
    );

```

```dart
class WaterBackground extends GameComponent {
  WaterBackground({
    required this.speed,
  });

  late Sprite sprite;
  late FragmentShader shader;
  double _timeElapsed = 0.0;
  final double speed;

  @override
  Future<void> onLoad() async {
    final sprite = await Sprite.load('water.png');

    final fragmentProgram = await FragmentProgram.fromAsset(
      'shaders/water_shader.frag',
    );
    shader = fragmentProgram.fragmentShader();
    // Set the texture
    shader.setImageSampler(0, sprite.image);

    // Set the resolution
    shader.setFloat(0, sprite.originalSize.x);
    shader.setFloat(1, sprite.originalSize.y);

    // Set the speed
    shader.setFloat(3, speed);

    paint.shader = shader;
  }

  @override
  void update(double dt) {
    super.update(dt);
    _timeElapsed += dt;
    shader.setFloat(2, _timeElapsed);
  }

  @override
  void onMount() {
    size = gameRef.map.size;
    super.onMount();
  }

  @override
  void render(Canvas canvas) {
    canvas.drawRect(Rect.fromLTWH(x, y, size.x, size.y), paint);
  }

  @override
  int get priority => LayerPriority.BACKGROUND;
}
```

**Comment by MikaReesu** [comment]
That's interesting that way! I didn't know I could use the layer priority like that! 

That's nice! Is there a difference between loading the map in json and in tmj?(Wondering since we had issues with opacity inside of tiled).

**Comment by RafaelBarbosatec** [comment]
There is no difference between `json` and `tmj`.
How did you try apply opacity in Tiled?
I don’t have any problem in apply opacity in a tileLayer:
<img width="204" alt="image" src="https://github.com/RafaelBarbosatec/bonfire/assets/10039275/1ca192c7-def5-4fed-ac1e-8dc68cfa12e6">

![image](https://github.com/RafaelBarbosatec/bonfire/assets/10039275/2525e445-6059-45e1-ba59-8291c8cd78d5)

**Comment by MikaReesu** [comment]
I applied it on the layer itself in Tiled.
