### ISSUE TITLE
[question]:  How can we change the sprite/animation of the SimplePlayer in game?

### ISSUE THREAD

**Issue by KevinNcc** [RafaelBarbosatec/bonfire#454]
### How can we help?

Hello Rafael,

Do you know a way to change the sprites or perhaps the animation (simpleDirectionAnimation) with new sprites for the SimplePlayer to change the skin of the player in game, with a keyboard key, or perhaps put a sprite in front of another?

Thank you for your answer ;) !

**Comment by RafaelBarbosatec** [comment]
Hi @KevinNcc !
To change de SimpleDirectionAnimation just call 'replaceAnimation' method.
https://bonfire-engine.github.io/#/doc/mixins?id=directionanimation

To do merge imagens you can use Image composition:

https://docs.flame-engine.org/latest/flame/rendering/images.html#imagecomposition

I did use this in a example and in SunnyPlace game.

**Comment by KevinNcc** [comment]
Hi @RafaelBarbosatec,
Thank you for your answers the 'replaceAnimation' method works just fine!

And on the composition side, I have some more issues.
Could you give me an example of how to use it with our Bonfire?   At the moment I have a sprite sheet, with idle, run, attack animation. Like we always do with Bonfire. 

What would be Image1 exactly in the case of Bonfire? Will this change many things in the "normal" behaviour of our game with Bonfire?

 I have the impression that we need to adapt a bit more compared than if we were only in Flame.

I would be very happy to see an implementation of this feature. 
Thank you very much for your help and time.

**Comment by RafaelBarbosatec** [comment]
Thanks! ☺️
About image composition, is not needed a custom implementation in bonfire. Just build your image how you want and crate a new SimpleDirectionAnimation and use it.

**Comment by RafaelBarbosatec** [comment]
We had a example using it in our example repository. I will check if it exists yet.

**Comment by KevinNcc** [comment]
I will try but if you have an example around that will be kind of you.

Thank you very much for your help.
