### ISSUE TITLE
[question]: deprecated files

### ISSUE THREAD

**Issue by shinriyo** [RafaelBarbosatec/bonfire#456]
### How can we help?

 These files are similar. Are they able to merge?
`example/assets/images/multi_scenario/hero/hero_multi_biome.png`
`example/assets/images/player/pirate.png`

**Comment by RafaelBarbosatec** [comment]
Hi @shinriyo !
Yes you can delete one.
Join to us Telegram Group: https://t.me/bonfire_engine
There is better to communicate.

**Comment by RafaelBarbosatec** [comment]
Duplicidade removida
