### ISSUE TITLE
[question]: Sensor size

### ISSUE THREAD

**Issue by MikaReesu** [RafaelBarbosatec/bonfire#458]
### How can we help?

Hello, I have a question concerning the Sensor. Is it possible to use the sensor in a different size than the size of the sprites used? 
I would like to be able to setup the size of the sensor. Is that possible?

Thank you very much.

**Comment by RafaelBarbosatec** [comment]
Hi @MikaReesu !
Just add your on `ShapeHitbox`:

```dart

    @override
    Future<void> onLoad() {
        add(RectangleHitbox(size:size));
        return super.onLoad();
    }

```

**Comment by MikaReesu** [comment]
I tried that in the past but didn't work but just tried and all good now. 

`RectangleHitbox(
        size: size / 2,
        position: Vector2(size.x / 2, size.y / 2),
        anchor: Anchor.center,
      ),`
      
I added that to center the collision box.

Thank you!
