### ISSUE TITLE
[question]: Map loading duration

### ISSUE THREAD

**Issue by MikaReesu** [RafaelBarbosatec/bonfire#461]
### How can we help?

Hello, 

Is there a way to know how long the loading of the map is gonna take?

For now, I'm using a hardcoded duration : 
```

Duration loadingDuration = const Duration(
    milliseconds: 800,
  );
delayToHideProgress: loadingDuration,
          progressTransitionDuration: loadingDuration,
```

I wanted to know if there was a way to just get the information about that.

Thank you very much for your help :)

**Comment by RafaelBarbosatec** [comment]
You don’t need set a specific duration.
The progress already show the time necessary to map load.
This features is only to adds a time more if needed.

**Comment by MikaReesu** [comment]
I understand that, but, I had to put a time, which is not necessarily enough because, the necessary time to load the map was apparently not enough. 

After the loading screen, we we were seing a sort of black screen before seing the map(on mac, windows and android).

That's why I assumed that I had to put hardcoded time to handle this issue.

**Comment by RafaelBarbosatec** [comment]
humm, strange. It's happen if load map from `url`.
Can you share a video of this behaviour?.
If it's really happen, maybe a solution for this is preload the assets before open de game.

**Comment by MikaReesu** [comment]
Where could I send you the video privately(I would prefer)?

How to preload assets? That seems interesting.

**Comment by RafaelBarbosatec** [comment]
You can find me in the our group of Telegram. https://t.me/bonfire_engine

**Comment by MikaReesu** [comment]
Thanks, I sent a message there.
