### ISSUE TITLE
moveTowardsTarget to use GravityForce2D[question]: 

### ISSUE THREAD

**Issue by swiftyui** [RafaelBarbosatec/bonfire#463]
### How can we help?

Hi :)

I'm busy creating a platformer game using bonfire and everything is working brilliantly, I know it is suggested to rather use flame, but I LOVE bonfire, I noticed the latest branch does have some work for platformer games and was wondering if it might be possible to either add gravity to the moveTowardsTarget? Otherwise it "bugs" out moving vertically towards a user, or maybe extend it to use the GravityForce2D?

**Comment by RafaelBarbosatec** [comment]
HI @swiftyui !
Yeah, nothing of this enemy behaviour was adapted to `EnemyPlatform`. You need do it your self.
Maybe I will create this methods do `EnemyPlatform` soon.

**Comment by swiftyui** [comment]
That would be brilliant, just want to give you a huge thanks! **Your work is awesome**!!

**Comment by RafaelBarbosatec** [comment]
Hi @swiftyui !
In the version `3.0.6` I will adds the param `movementAxis` in this method. It's can help you. You will might set `MovementAxis.horizontal` to do only horizontal movements.

**Comment by arnovanzyl** [comment]
This would be absolutely brilliant! :) Thank you @RafaelBarbosatec!
And keep up the brilliant work! :)

**Comment by swiftyui** [comment]
![Screen Recording 2023-11-09 at 16 16 50](https://github.com/RafaelBarbosatec/bonfire/assets/32429591/185156b3-6a90-4510-bea1-227ef2d7ac3e)
Can confirm this is working **beatifully**! Thanks @RafaelBarbosatec  :)
