### ISSUE TITLE
[question]: The README's game

### ISSUE THREAD

**Issue by shinriyo** [RafaelBarbosatec/bonfire#464]
### How can we help?

<img width="386" alt="Screenshot 2023-11-05 at 22 26 37" src="https://github.com/RafaelBarbosatec/bonfire/assets/396927/d1707122-fff7-40dd-8fb6-8c6f798fcfdb">
Where is the sample?
I like the animatable button.

**Comment by RafaelBarbosatec** [comment]
Hi @shinriyo !
This is my personal project. It's in a private repository. ☺️
