### ISSUE TITLE
[question]: Pushable from PLAYER only feature

### ISSUE THREAD

**Issue by shinriyo** [RafaelBarbosatec/bonfire#470]
### How can we help?

`Attackable` has `AttackFromEnum` enum.
But `Pushable` doesn't have it.
So, the enemies also push the barrel.

**Comment by RafaelBarbosatec** [comment]
https://github.com/RafaelBarbosatec/bonfire/assets/10039275/4b48e322-e1b1-49e1-a8d2-a1c6f4b9157e

Next version will be available this feature and per-cel movements.

```dart
void setupPushable({
    bool? enabled,
    PushableFromEnum? pushableFrom,
    bool? pushPerCellEnabled,
    Vector2? cellSize,
    double? pushPerCellDuration,
    Curve? pushPerCellCurve,
  })
```

**Comment by shinriyo** [comment]
Thank you.
Will you add it feature in `Pushable` class?

**Comment by RafaelBarbosatec** [comment]
Yes! This `setup` is of `Pushable` mixin

**Comment by shinriyo** [comment]
your mov file's moving is nice

**Comment by RafaelBarbosatec** [comment]
Created  also the mixin `MovePerCell` to be used in `Movement` components to move per cell.

**Comment by shinriyo** [comment]
í it released?
