### ISSUE TITLE
onTapDown?

### ISSUE THREAD

**Issue by guto-alves** [RafaelBarbosatec/bonfire#480]
Hi, I saw BonfireWidget's onTapDown parameter was removed in version 3.0.0, what's the best way to get the same result now?

**Comment by RafaelBarbosatec** [comment]
Hi @guto-alves !
What do you need to do?
To get the tap gesture of game screen, you can create a GameComponent just do it:

```dart

class MyGameTapGesture extends GameComponent with TapGesture {
  @override
  void onTap() {}

  @override
  void onTapDownScreen(GestureEvent event) {
   // do something when tap down on the screen.
    super.onTapDownScreen(event);
  }

 @override
  void onTapUpScreen(GestureEvent event) {
   // do something when tap up on the screen.
    super.onTapDownScreen(event);
  }

  // keep this component always visible because only visible components can handle gestures event.
  @override
  bool get isVisible => true;
}

```

and adds it in the game:


```dart
return BonfireWidget(
  components:[MyGameTapGesture()]
)
```

**Comment by guto-alves** [comment]
Exactly what I needed! Thank you very much for your help.

**Comment by chongbo2013** [comment]
MyBarHealthComponent  onTap not call
class KnightInterface extends GameInterface {
  late Sprite keySprite;

  @override
  Future<void> onLoad() async {
    keySprite = await Sprite.load('items/key_silver.png');
    add(MyBarHealthComponent());
    return super.onLoad();
  }


  @override
  void render(Canvas canvas) {
    try {
      _drawKey(canvas);
    } catch (e) {}
    super.render(canvas);
  }

  void _drawKey(Canvas c) {
    if (gameRef.player != null && (gameRef.player as Swordsman).containKey) {
      keySprite.renderRect(c, Rect.fromLTWH(150, 20, 35, 30));
    }
  }

}

**Comment by RafaelBarbosatec** [comment]
Hi @chongbo2013 !
Please try onTapComponent.
https://github.com/RafaelBarbosatec/bonfire/blob/master/example%2Flib%2Fshared%2Finterface%2Fknight_interface.dart
