### ISSUE TITLE
[Bug]: Error: The getter 'onLoadFuture' isn't defined for the class 'Game'.

### ISSUE THREAD

**Issue by AgnelSelvan** [RafaelBarbosatec/bonfire#485]
### What happened?

I'm using Flutter version `3.16.9`. Created a new Flutter Project, imported flame and bonfire packages, added **BonfireWidget**, and ran the application. I was getting the below errors. The issue I faced was running the project on MacOS as well as on Android.

../../../.pub-cache/hosted/pub.dev/bonfire-3.3.0/lib/base/listener_game_widget.dart:176:36: Error: The getter 'onLoadFuture' isn't defined for the class 'Game'.
 - 'Game' is from 'package:flame/src/game/game.dart' ('../../../.pub-cache/hosted/pub.dev/flame-1.15.0/lib/src/game/game.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'onLoadFuture'.
        final onLoad = currentGame.onLoadFuture;
                                   ^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

Command PhaseScriptExecution failed with a nonzero exit code
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')

Bonfire and Flame version
```dart
      bonfire: ^3.3.0
      flame: ^1.14.0
```

game.dart
```dart
import 'package:bonfire/bonfire.dart';
import 'package:flutter/material.dart';
import 'package:flutter_application_1/character.dart';
import 'package:flutter_application_1/player.dart';

class GameScreen extends StatelessWidget {
  const GameScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return BonfireWidget(
      player: HunterCharacter(
        position: Vector2.all(50),
        size: Vector2.all(64) * 0.7,
        spriteSheet: PlayerSprite.spriteSheet,
      ),
      map: WorldMapByTiled(
        TiledReader.asset('map_one.json'),
        forceTileSize: Vector2(32, 32),
      ),
      cameraConfig: CameraConfig(
        zoom: 2,
      ),
      joystick: Joystick(
        directional: JoystickDirectional(),
        keyboardConfig: KeyboardConfig(
          directionalKeys: KeyboardDirectionalKeys.wasd(),
          acceptedKeys: [],
        ),
      ),
    );
  }
}

```

main.dart
```dart
import 'package:flutter/material.dart';
import 'package:flutter_application_1/game.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const GameScreen(),
    );
  }
}

```
<img width="1121" alt="Screenshot 2024-02-09 at 7 42 32 PM" src="https://github.com/RafaelBarbosatec/bonfire/assets/47639176/bb2bd6d2-c897-423a-94ab-09833708cff5">

### Steps to reproduce?

```Markdown
1. Create a new flutter project
2. Add bonfire and flame dependency
3. Add the BonfireWidget and run the project.
```

### What did you expect to happen?

The game should be open when running the project.

### Bonfire version

bonfire: ^3.3.0

**Comment by RafaelBarbosatec** [comment]
Hi @AgnelSelvan. At the moment try stay fixed the flame version in your project:
flame: 1.4.0

As soon as possible I will update the flame version.

**Comment by AgnelSelvan** [comment]
Okay Thanks, @RafaelBarbosatec

**Comment by RafaelBarbosatec** [comment]
Version `3.4.0` available
