### ISSUE TITLE
[question]: How can I create dash game with infinity map 

### ISSUE THREAD

**Issue by vynln92** [RafaelBarbosatec/bonfire#496]
### How can we help?

First of all, I would like to thank you for creating Bonfire, which is super easy and fast for game development. I started fall in love with this.

I would like to create a dash game with infinity map just like Flappy bird for example.
How can I archive this with Bonfire. Are there any example or document about this?

Thank you!

**Comment by RafaelBarbosatec** [comment]
Hi @vynln92 !
It's a good question!
As pass goes by time I focused in top-down game and I not think about this kind of game.
But, I think that is possible . You can use the parallax present in the Bonfire example, and create a component that will be generate the obstacles and moving to left.

I can create a example and release here when I got a little time.

**Comment by RafaelBarbosatec** [comment]
Here you go! 
https://github.com/RafaelBarbosatec/bonfire_flappy_bird

https://github.com/RafaelBarbosatec/bonfire/assets/10039275/e7e43f57-fa24-47b2-b92c-4a0f39410f2d

**Comment by vynln92** [comment]
Thanks for your great work @RafaelBarbosatec. Love Bonfire very much <3
