### ISSUE TITLE
Can KeyboardConfig only select one option? wasd or arrows ?

### ISSUE THREAD

**Issue by devchenli** [RafaelBarbosatec/bonfire#507]
### How can we help?

   keyboardConfig: KeyboardConfig(
            directionalKeys: KeyboardDirectionalKeys.arrows(),
            acceptedKeys: [
              LogicalKeyboardKey.space,
            ],
          ),

How to set up support for both KeyboardDirectionKeys. arrows() and KeyboardDirectionKeys. wasd() ?

**Comment by RafaelBarbosatec** [comment]
Hi @devchenli !
Thanks for this question.
It's a good point. It's not possible at the moment. I'll enable this in next release.
