### ISSUE TITLE
[Bug]: When adding multiple HitBoxes, the second and subsequent tests are incorrect

### ISSUE THREAD

**Issue by nyuntaka** [RafaelBarbosatec/bonfire#511]
### What happened?

When adding multiple HitBoxes, the second and subsequent tests are incorrect. I think this is a bug.
![hitbox0r](https://github.com/RafaelBarbosatec/bonfire/assets/14065274/bb8c65d7-633a-4235-aa0d-f49b1f8a10b3)
![hitbox1r](https://github.com/RafaelBarbosatec/bonfire/assets/14065274/054ea465-9977-4519-af2f-cc44e8298848)
![hitbox2r](https://github.com/RafaelBarbosatec/bonfire/assets/14065274/95966bb0-2ffa-41f1-b8d6-12873ef6dcb0)

### Steps to reproduce?

```Markdown
CollisionMapComponent collis = CollisionMapComponent(
      position: Vector2.zero(),
      size: Vector2.zero(),
      collisions: [
        RectangleHitbox(
          position: Vector2.all(200),
          size: Vector2.all(100),
        ),
        RectangleHitbox(
          position: Vector2.all(300),
          size: Vector2.all(100),
        ),
        CircleHitbox(
          radius: 50,
          position: Vector2.all(400),
        )
      ],
    );

    return LayoutBuilder(
      builder: (context, constraints) {
        return BonfireWidget(
          components: [collis],
          showCollisionArea: true,
          ...
```
This bug also occurs with GameComponent other than CollisionMapComponent.

### What did you expect to happen?

I think the second and subsequent ones should have the same result as the first.

### Bonfire version

3.8.5

### Relevant log output

```Shell
No response
```

**Comment by RafaelBarbosatec** [comment]
Hi @nyuntaka ! 
Thanks for this issue.
In the moment I consider only the first hotbox to handle collision. I will try improve this point.
Thank you!

**Comment by nyuntaka** [comment]
Until then, I will instead use multiple GameDecorations with one HitBox added.
Thank you.

**Comment by nyuntaka** [comment]
I was able to confirm that it was fixed.
thank you very much.
