### ISSUE TITLE
[Bug]: When using a fixed resolution, the joystick appears in the wrong position, and it's unable to properly control the player.

### ISSUE THREAD

**Issue by devchenli** [RafaelBarbosatec/bonfire#526]
### What happened?

 return BonfireWidget(
      cameraConfig: CameraConfig(
        resolution: Vector2(1280, 720),
        zoom: 3,
      )....

<img width="684" alt="截屏2024-06-07 09 21 04" src="https://github.com/RafaelBarbosatec/bonfire/assets/46481943/cbb65aab-793d-4dd7-99bf-a27a7d168c93">

### Steps to reproduce?

```Markdown
Just set : 

cameraConfig: CameraConfig(
        resolution: Vector2(1280, 720),
        zoom: 3,
      ),

    playerControllers: [
        Joystick(
          directional: JoystickDirectional(),
          actions: [
            JoystickAction(
              actionId: 1,
              margin: const EdgeInsets.all(50),
            ),
          ],
        ),.....

and the joystick appears in the wrong position.
```

### What did you expect to happen?

It's a bug ?

### Bonfire version

3.9.4

**Comment by RafaelBarbosatec** [comment]
Fixed in Version 3.9.5
