### ISSUE TITLE
[question]: Is it possible to reload whole game?

### ISSUE THREAD

**Issue by dvmatyun** [RafaelBarbosatec/bonfire#536]
### How can we help?

How do I reload whole game? Removing `BonfireWidget` widget from the tree and then adding it again does not help - the map is not getting loaded for some reason. Or is it intended for game widget to NEVER leave the tree once its mounted?
So this code does not work (game map just grey background after reload):
```
  bool isLoading = false;
  late final Timer timer;

  /* #region Lifecycle */
  @override
  void initState() {
    super.initState();
    timer = Timer.periodic(const Duration(seconds: 5), (Timer t) {
      setState(() {
        isLoading = !isLoading;
      });
    });
  }


  @override
  Widget build(BuildContext context) {
    if (isLoading) {
      return Material(
        child: Center(
          child: CircularProgressIndicator(),
        ),
      );
    }
    return Material(
      color: Colors.transparent,
      child: BonfireWidget(
        /* here is just regular game config */
      ),
    );
  }
```

**Comment by dvmatyun** [comment]
Hm, solved it with Navigator.pushReplacement. But still a question: why it does not work with my example? (Just to learn a little bit more about how engine works)

**Comment by RafaelBarbosatec** [comment]
Yes, it's possible reload a game. This estrategic is good. Just do a useState updating the Bonfire widget key. This will load the game again. I do it in the Flappy bird game.
