### ISSUE TITLE
[question]: How to play sound on animation start?

### ISSUE THREAD

**Issue by dvmatyun** [RafaelBarbosatec/bonfire#537]
### How can we help?

How do I play some sound effect when movement animation starts? (on each loop) So imagine you have a sprite sheet of walking man, and you want to play footstep sound effect each time the foot hits the ground (and imagine it is the first frame in spritesheet).
PS Im talking about this in context of enemies, so `SimpleEnemy` \ `Enemy` \ `DirectionAnimation` classes

**Comment by RafaelBarbosatec** [comment]
Hi @dvmatyun . You can do override the 'onMove' method and try look to the frame animation index . or put a interval.
In new version you can get this with `animation.currentIndex` or `animation.fastAnimationcurrentIndex`.

**Comment by dvmatyun** [comment]
@RafaelBarbosatec for some reason both `_current` and `_fastAnimation` animations are private. Guess I will just fork the implementation and make getters for them. Anyway, thanks!

**Comment by RafaelBarbosatec** [comment]
The new version it is public. Didn't?
