### ISSUE TITLE
[question]: Where can I find the root call of `BonfireGame void update(double dt)` method for time measurement?

### ISSUE THREAD

**Issue by dvmatyun** [RafaelBarbosatec/bonfire#539]
### How can we help?

Im curious how time implementation for the engine looks like to implement server-client synchronization, can you tell me where can I see the root call of time update method `void update(double dt)` in Bonfire engine (BonfireGame class I suppose it is, and who passes a `dt` to that method)?

**Comment by RafaelBarbosatec** [comment]
Hi @dvmatyun !
This game loop is provided by `Flame` package. You can se this implementation in : [RenderGameWidget](https://github.com/flame-engine/flame/blob/main/packages/flame/lib/src/game/game_render_box.dart) using [GameLoop](https://github.com/flame-engine/flame/blob/main/packages/flame/lib/src/game/game_loop.dart)

**Comment by RafaelBarbosatec** [comment]
About multiplayer game. I was started a project using Dart. Please check bonfire_multiplayer. Maybe this could help you.
