### ISSUE TITLE
[Bug]: monster IA on collisions

### ISSUE THREAD

**Issue by mrleao** [RafaelBarbosatec/bonfire#540]
### What happened?

How can we make the monsters have the intelligence to avoid objects on the map and chase the target?

see the movie

https://github.com/user-attachments/assets/ce1b33f7-e757-4352-a113-76198c304239

The behavior of enemies when colliding with other enemies or objects on the map means that the enemy does not change route to find the player

O comportante dos inimigos ao colidir com outros inimigos ou objetos do mapa fazem com que o inimigo não mude de rota para encontrar o jogador

### What did you expect to happen?

When a character enters a monster's screen, its behavior should be to chase the player, and this happens when there are no obstacles on the map, because when the monster collides with a tree or another monster it cannot trace a new route to the player. .

Quando um personagem entra na tela de um monstro, seu coportamento deveria ser perserguir o player, e isso acontece quando não existem obstaculos no mapa, pois quando o monstro colide com uma arvore ou com outro monstro ele não conseguir traçar um novo perscurso até o player. 

### Bonfire version

3.4.1

**Comment by RafaelBarbosatec** [comment]
Hi @mrleao !
Seen your video. the collision area of your enemy is too big to pass between these other collisions (two trees).
In the moment this method provided by Bonfire not have AI to find a solution how chasing your player. He only try see the player and try move in her direction.
But if you need you can create a role or AI to do it, exploring the [path_finding](https://bonfire-engine.github.io/#/doc/path_finding?id=pathfinding)
