### ISSUE TITLE
[question]: receiveDamage changed to bool

### ISSUE THREAD

**Issue by MikaReesu** [RafaelBarbosatec/bonfire#541]
### How can we help?

Hello, 
I recently migrated my project to the version 3.9.7. I noticed that this function was removed and replaced by a bool : 
```void receiveDamage(AttackOriginEnum attacker, double damage, identify) {```

Now, I'm wondering what we are suppose to use to replicate this. 

I was thinking about onRemoveLife but we can only get the life, and we don't know who the attacker is.
 
The new receiveDamage is now a bool, so I find it hard to imagine how we are suppose to use it in the player for example. 

Let's say, that there is an enemy attacking the player with poison, the receiveDamage was useful because I could know who was the attacker and I could apply something specific to the player, for example that he was poisoned. 

Thank you for your help and have a good day.

**Comment by RafaelBarbosatec** [comment]
Hi @MikaReesu !
Thanks for contacting.
Yeah, it's make sense. In the moment you can do override in receiveDamage and pay attention to return of the super.receiveDamage, if true you can do your logic with base Attacker.

But, it's a good idea adds at onRemovedLife this informations. I'll adds it.

**Comment by MikaReesu** [comment]
At the moment, I can't do receiveDamage it was deleted. 

But yes, it could be a good idea to add it to onRemoveLife? 

Was there a purpose to have receiveDamage and onRemoveLife? It seems to be a duplicated to me.

**Comment by RafaelBarbosatec** [comment]
Each have a different role. Maybe the name isn't helping us. ☺️

**Comment by MikaReesu** [comment]
Yes, for me it does mean the same.

onReceiveDamage, would be a bit better in my opinion with the attacker and the damage of course
What was the use of identity?

**Comment by MikaReesu** [comment]
Was the purpose of onRemoveLife to be able to use it outside of the player for example?

**Comment by RafaelBarbosatec** [comment]
So, the idia of onRemoveLife is notify when the Attackable reduce life. Because not it all attack received cause damage. And receiveDamage is verify if the damage recived can remove life or not.

**Comment by MikaReesu** [comment]
In that case why not to have only one function for this, something like onUnderAttack(damage, attacker, identity)?

In this way, we just have to check if there is damage or not ourselves. It is less confusing for us when we develop and in this way we have only one function. What do you think?

**Comment by MikaReesu** [comment]
I still was wondering, since I can't use ```void receiveDamage(AttackOriginEnum attacker, double damage, identify) {```
at the moment, what am I suppose to use?

**Comment by RafaelBarbosatec** [comment]
I will fix this today. And then you can do override the `onReceiveDamage`

**Comment by RafaelBarbosatec** [comment]
Available in `3.9.8`

**Comment by MikaReesu** [comment]
Thank you, I'll check that!

**Comment by MikaReesu** [comment]
Perfect, thank you!
