### ISSUE TITLE
[Bug]: isDead not updated to true after player death

### ISSUE THREAD

**Issue by MikaReesu** [RafaelBarbosatec/bonfire#542]
### What happened?

Hello,

I have a GameDecoration with a sensor GameComponent and when the player goes on it, I get a "Cannot find reference $BonfireGameInterface in the component tree" when he is suppose to be dead. 

I had a few checks with the gameRef, gameRef.player and !gameRef.player.isDead. I noticed that even though the player had no life, it was still executed.

Please look at the picture below, the life of the player is at 0.0 but the isDead is at false and it should be at true.
<img width="241" alt="image" src="https://github.com/user-attachments/assets/429a1d17-8a99-4543-bcb8-686d0d1a83fa">

### Steps to reproduce?

```Markdown
1. I guess use a extends GameDecoration with Sensor<GameComponent>
2. In the onContactExit or onContact, add a line to do a direct action that will need the gameRef like gameRef.player!.receiveDamage(AttackOriginEnum.ENEMY, 1, 0);
3. Run it with the debug point and when the player as no life, check the life and the isDead variables.

Normally the exception shouldn't appear as long a you use the isDead value but in that case since the life is at 0.0 and the isDead was false it was triggering the exception.
```

### What did you expect to happen?

I expected the isDead to be true when life is at 0.0.

### Bonfire version

3.9.7

**Comment by RafaelBarbosatec** [comment]
Hi @MikaReesu !
I can't reproduce this case. Maybe you been do override `receiveDamage` in your player and not call a `super.`

**Comment by MikaReesu** [comment]
I'll check how it is with the 3.9.8 and I will see if I still have the same issue. 

But still, it's weird that life was at 0.0 and isDead was not at true.

I didn't have this issue in the past with the previous versions.

**Comment by RafaelBarbosatec** [comment]
If this problem yet keep. Please reopen this issue and share your code source.
This feature was tested and work well.
