### ISSUE TITLE
[question]: How do you implement Pushable?

### ISSUE THREAD

**Issue by KevinNcc** [RafaelBarbosatec/bonfire#543]
### How can we help?

Hi,
When my player move toward an enemy he can push it, how can I disable it?

I tried the mixin Pushable but I couldn't make it work with. 
Could you provide me a working example for modifying the status of the push to true or false? 

Thank you very much.

**Comment by RafaelBarbosatec** [comment]
Hi @KevinNcc !
If you don't want you enemy that contains the mixin `BlockMovementCollision` could be pushable you must set yout bodyType to `static`:

```dart
setupBlockMovementCollision(
      bodyType: BodyType.static,
    );

```

**Comment by KevinNcc** [comment]
Hi, it's working perfectly, thank you!
