### ISSUE TITLE
[Bug]: simpleAttackMelee when attacking other directions are not working

### ISSUE THREAD

**Issue by ErtasBurak** [RafaelBarbosatec/bonfire#548]
### What happened?

the player just attacks one direction. before the change of simpleAttackMelee the other directions were working

### Steps to reproduce?

```Markdown
1. create player
2. set simpleAttackMelee to joystick action
3. attack
```

### What did you expect to happen?

should attack to that direction the player moves

### Bonfire version

3.9.8

**Comment by RafaelBarbosatec** [comment]
Hi @ErtasBurak .
Could you give more information?
Video or your source code?
This function works well e the example projects.

**Comment by ErtasBurak** [comment]
I found the issue. It's because of the Hitbox in onLoad().
