### ISSUE TITLE
GameDecoration frontFromPlayer=true does not render on top of Player Object

### ISSUE THREAD

**Issue by PonthepYJ** [RafaelBarbosatec/bonfire#55]
I try to create a decoration object by bonfire: ^0.6.18, I set **frontFromPlayer:true** as expected it to be rendered on top of Player object but the decoration still render below Player Object.

Testing on Web and Android emulator, both are got the same result. 

 Jerry(this.initPosition)
      : super.sprite(
            Sprite(
              "itens/jerry.png",
            ),
            width: 192,
            height: 67,
            initPosition: initPosition,
            frontFromPlayer: true) {
    _textConfig = TextConfig(
      color: Colors.white,
      fontSize: 10,
    );
  }

**Comment by RafaelBarbosatec** [comment]
Hi @PonthepYJ ! I cannot reproduce this problem. In my tests it worked.

**Comment by PonthepYJ** [comment]
I have done fresh download from github, and add only one line of code "frontFromPlayer:true" to the spikes.dart. The spike still display behind the player on both web and android emulator as you see from my captured screen below.I expected player to walk behind the decoration object.

![Screen Shot 2020-08-19 at 5 52 50 AM](https://user-images.githubusercontent.com/56213394/90573312-58629100-e1e0-11ea-8234-1e5f0c9bb7da.png)
![Screen Shot 2020-08-19 at 5 54 42 AM](https://user-images.githubusercontent.com/56213394/90573371-85af3f00-e1e0-11ea-81dd-f685b5e461c7.png)

**Comment by RafaelBarbosatec** [comment]
hmm. I'm going to do the same test you showed me and see if I can identify anything. Thank you.

**Comment by RafaelBarbosatec** [comment]
I was able to identify the problem. It occurs on the map loaded by Tiled. I will be running fix.

Thank you very much for contacting us.

**Comment by RafaelBarbosatec** [comment]
Please check in version 0.6.19.

**Comment by PonthepYJ** [comment]
> Please check in version 0.6.19.

Thanks for your sincerely support.
