### ISSUE TITLE
[question]: How to prevent players from walking out of this place?

### ISSUE THREAD

**Issue by kjxbyz** [RafaelBarbosatec/bonfire#550]
### How can we help?

I'm a beginner and have a question, how to prevent players from walking out of this place? Thank you.

![WX20240811-203214@2x](https://github.com/user-attachments/assets/7b49a381-4848-4384-a3b4-c750b02a547b)

**Comment by RafaelBarbosatec** [comment]
Hi @kjxbyz !
Check out the collision of this wall. Probably have a space without collision give permission to pass.
To show the collisions just set showCollisionArea to true in Bonfire widget and run again.

**Comment by RafaelBarbosatec** [comment]
I need separate some time to update this project. ☺️
