### ISSUE TITLE
[Bug]: Update flame to 1.19.0

### ISSUE THREAD

**Issue by kjxbyz** [RafaelBarbosatec/bonfire#554]
### What happened?

```
Because fafarunner depends on bonfire 3.10.0 which depends on flame 1.18.0, flame 1.18.0 is required.
So, because fafarunner depends on flame 1.19.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on bonfire: flutter pub add bonfire:^3.6.2

make: *** [get] Error 1
```

### Steps to reproduce?

```Markdown
flutter pub get
```

### What did you expect to happen?

Update `flame` to `1.19.0`

### Bonfire version

1.10.0

**Comment by RafaelBarbosatec** [comment]
Hi @kjxbyz !
Why do you import flame in your project?
You just need bonfire to bonfire projects.
I'll take a look in this new version of Flame to update in Bonfire.

**Comment by kjxbyz** [comment]
Thank you

**Comment by RafaelBarbosatec** [comment]
Updated in the latest version
