### ISSUE TITLE
[question]: How do I drag to move camera?

### ISSUE THREAD

**Issue by chuonglam** [RafaelBarbosatec/bonfire#555]
### How can we help?

Hello, 
I'm new to Bonfire and don't know how to drag to move the camera, like this:
https://www.youtube.com/watch?v=LjRY86YT8UM&ab_channel=kuhchan

Is there any way to do this with Bonfire or should I handle it manually using drag gesture?

**Comment by RafaelBarbosatec** [comment]
Hi @chuonglam !
You can use in your player the mixin MoveCameraUsingGesture.

**Comment by RafaelBarbosatec** [comment]
https://bonfire-engine.github.io/#/doc/input?id=movecamerausinggesture
