### ISSUE TITLE
[Bug]: moveAlongThePath not working after update.

### ISSUE THREAD

**Issue by flea-Bear** [RafaelBarbosatec/bonfire#559]
### What happened?

moveAlongThePath was working after following Bonfire tower defense tutorial. after upgrading to 3.10.3 the enemies appear and start animating but do not move.

### Steps to reproduce?

```Markdown
1. use tower defense github exact copy.
2. enemies moveAlongThePath using 3.7.0. (the version in the pubspec.yaml)
3. upgraded to newest dart and bonfire 3.10.3
4. enemies show up but don't move
```

### What did you expect to happen?

Enemies to move along path, like they did before.

### Bonfire version

3.7.0 worked, 3.10.3 no work

**Comment by flea-Bear** [comment]
when i downgrade bonfire to 3.7.0 and did a dependency override flame to 1.18.0 it worked again. maybe there is a problem so maybe the problem is in 3.10.0 when a-star-algorithm package was updated.

**Comment by RafaelBarbosatec** [comment]
Hi @flea-Bear !
Take a look again to the repository. I updated.
The problem was the order method in 'onMount'.
https://github.com/RafaelBarbosatec/bonfire_tower_defence/commit/10a26442a8664614b9c3f9c1a4e937585c8bb2d0
