### ISSUE TITLE
[question]: MiniMap Centering and Display Issues with Zoom Levels Other than 1.0

### ISSUE THREAD

**Issue by qulvmp6** [RafaelBarbosatec/bonfire#564]
### How can we help?

Hi, I encountered two issues while using the `MiniMap` widget with a `zoom` value other than `1.0`. Specifically, I noticed that when `zoom` wasn’t equal to `1.0`, the minimap’s center no longer aligned with the camera position, resulting in an off-centered display. Additionally, when setting `zoom` to a value less than `1.0`, while the minimap area expanded as expected, components (such as enemies) outside the camera view were not being displayed.

To try to address these issues, I made a couple of adjustments, but I would appreciate any feedback or confirmation on whether these changes align with your intentions for the code:

1. **Retrieving All Game Components**:
   - I replaced `widget.game.visibles()` with `widget.game.query()` in the `MiniMap` widget. Since `visibles()` only returns components within the camera view, it seems to limit what appears on the minimap when zoom levels change. By using `query()`, I’m able to retrieve all `GameComponents` (including those outside the camera view), which allows the minimap to display everything in the game area regardless of zoom.

2. **Centering the Camera Position on the Minimap with Zoom**:
   - In the `MiniMapCanvas` class, I adjusted the `canvas.translate` logic to try to keep the minimap centered on the `cameraPosition`, even with zoom adjustments. The modified code for `canvas.translate` now looks like this:

     
     canvas.translate(
       -cameraPosition.x * scale + size.width / 2 - (gameSize.x * scale) / 2,
       -cameraPosition.y * scale + size.height / 2 - (gameSize.y * scale) / 2,
     );
     

   This adjustment seems to ensure that the `cameraPosition` remains centered on the minimap, regardless of the zoom level. After testing, this approach appears to address the centering and display issues, but I’d appreciate if you could confirm whether this is the best way to approach it.

Thank you for this fantastic library, and I hope these adjustments are useful. I look forward to any insights you might have on these changes!

**Comment by RafaelBarbosatec** [comment]
Hi @qulvmp6 !
It's amazing! Thanks so much for this reporting.
This feature is experimental yet.
It's so far of to be a good feature.

I wil so glad with you open a PR with this improvements!

**Comment by qulvmp6** [comment]
Thank you for your response! 

I’ll try the PR in a few days to submit these changes.

**Comment by RafaelBarbosatec** [comment]
Thanks for your contribution!
