### ISSUE TITLE
Tap movement instead of joystick?

### ISSUE THREAD

**Issue by FahimF** [RafaelBarbosatec/bonfire#64]
Would it be possible to add tap handling to move the player (or to carry game actions) instead of the virtual joystick? This would help for games such as adventure games where the user might want to simply tap on various locations on screen instead of guiding the player via joystick.

**Comment by RafaelBarbosatec** [comment]
Good idea. I hadn't thought of that scenario. Currently it would be possible using Mixins TapGesture or PointerDetector.
 But it would have to remove the obligation of the Joystick.
I will be thinking of mechanisms for this scenario. If you want to contribute with PR you will also be welcome.😊

**Comment by FahimF** [comment]
@RafaelBarbosatec Thanks :) I had actually been planning to do exactly what you suggested - use the Tap Gesture detector - but then realized that there was a hard requirement of the joystick being present ... But will look at it tomorrow and see if I can perhaps get this in as a PR without making too many breaking changes 😄

**Comment by FahimF** [comment]
@RafaelBarbosatec I have some basic changes in place which make the Joystick optional - it is on by default but if it's not present, then related functionality is not activated. I have also updated the example project to have two options per map type - one with Joystick one without.

However, the maps without Joysticks currently do not have any control mechanism at all 😄 I have to fix that - or at least investigate how I would go about doing that. So didn't send you a PR yet because I wanted to look at that option too before I sent a PR. But in case you're interested, the changes up to now can be seen in my fork here:
https://github.com/FahimF/bonfire/commit/153a90fb6337ec02d43e6fea35cd8fb8954e304f

**Comment by RafaelBarbosatec** [comment]
Beautiful @FahimF !
 looks very good to me. I am waiting for the PR.

**Comment by FahimF** [comment]
@RafaelBarbosatec If you prefer that I send you a PR for what I have up to now, I can do that. But if you'd rather that there be some provision for the tap handling as well, I can wait on the PR till I get that part done too ...

Currently changing the `TapGesture` mixin to allow it to be added to `RPGGame` - not sure if that change will affect anything else and so wanted to make the changes, test and then get back to you. I realize that the tap handling will not cover all scenarios but was thinking of adding some basic player movement as default and then allow the developer to override that to provide their own tap handling implementation if that's what they want ...

**Comment by RafaelBarbosatec** [comment]
'TapGesture' is specific to 'GameComponent' so it will not work in 'RPGGame'.
'RPGGame' already listen gestures with 'PointerDetector'. The Ideal would be to implement this using these events.
Perhaps creating a specific mixin to listen to tap in the world. And then we make the player's movement system up to that point.

**Comment by FahimF** [comment]
I did notice that `TapGesture` had a check for `GameComponent` and was in the process of adding another check for `RPGGame`. But I probably didn't understand all the internal connections totally 😁 

So will go ahead and look at implementing it via `PointerDetector` as you suggested.

**Comment by FahimF** [comment]
@RafaelBarbosatec OK, that took a bit of work due to the approach I took 😄 Basically, I opted to change all the gesture actions to return true/false based on whether the gesture handlers actually handled the gesture or not. Then, at the `RPGGame` level, I check if the gesture was handled (meaning that there was a component at the tap/gesture point that took some action) or not and if the gesture was not handled, we can allow a way for the user to take some custom actions ...

For example, if the joystick is not enabled, then you can by default have the `RPGGame` class move the player to the position that was tapped but allow the developer to override that by providing their own custom tap (or drag) handlers. I didn't do the player movement part but I have verified that taps on objects (such as the draggable barrel) are handled correctly by the existing code and that non-handled taps now register as game screen taps.

I wanted to see what you thought before continuing on to the final step - adding default tap handling in `RPGGame`. So please let me know what you think ...

**Comment by RafaelBarbosatec** [comment]
Hi! Sorry for the delay in responding. I found your approach very cool! I don't think I would have a problem implementing it that way. Yes, you can continue.

**Comment by KyleKun** [comment]
Hey @FahimF 

Are you still working on it? I would also like to see the results 😄

**Comment by FahimF** [comment]
@RafaelBarbosatec @KyleKun The initial work is in my fork - that completed the approach that I was talking about except for implementing some sort of default tap handling. That part is not there since I got distracted with several different things. But what is there (if merged in) should allow turning off the joystick handling and if you want tap handling after that, you'd just need to implement it in your game as you need ...

**Comment by KyleKun** [comment]
Got it, I might not be able to work on this feature to handle default tap as well for now but thanks for the clarification!

**Comment by RafaelBarbosatec** [comment]
@FahimF I started a basic system of movement by click and it is in `develop` branch. So far I am not executing an algorithm to trace a course deviating from obstacles. If you want to continue, feel free.
I created a JoystickController called `TouchToPosition`.
And in the player the movement is in SimplePlayer on line 302.

**Comment by RafaelBarbosatec** [comment]
Available in 1.0.0 version
