### ISSUE TITLE
the tiled not support image layer?

### ISSUE THREAD

**Issue by diybl** [RafaelBarbosatec/bonfire#76]

**Comment by diybl** [comment]
Future<void> _load(TiledMap tiledMap) async {
    await Future.forEach(tiledMap.layers, (layer) async {
      if (layer is TileLayer) {
        await _addTileLayer(layer);
      }
      if (layer is ObjectGroup) {
        _addObjects(layer);
        _countObjects++;
      }
    });
  }

i found that there is no imagelayer type

**Comment by bonfire-engine** [comment]
Hi @diybl ! 
Thank you for the contact. It doesn't really support imagelayer yet.
I will be studying the possibility of adding.
If you are looking to add a backgound to the game you can use the BonfireTiledWidget parameter `background`

**Comment by RafaelBarbosatec** [comment]
Available in version 1.12.0
