### ISSUE TITLE
Add polygon collision detection

### ISSUE THREAD

**Issue by kuyum** [RafaelBarbosatec/bonfire#87]
First, sorry for my poor English.
How about add polygon collision detection? 
Polygon collision detection is useful in many cases, although it is more complicated than the Rectangle collision detection.
To reduce the computing, each polygon stores its outsideBox rectangle((minX, minY),(maxX, maxY)).
Detect the outsideBox first, if there is no collision, return false. If there is a collision, continue to have the rectangleToPolygon detection or polygonToPolygon detection.
Here is a reference package [collision_check](https://pub.dev/packages/collision_check). May it could do some help.

**Comment by RafaelBarbosatec** [comment]
Hi @kuyum !
Thanks for contact!
I thought your suggestion was really cool. I will be evaluating this implementation. If you can try to contribute and submit a pull request to the 1.0.0-rc branch. Would be great

**Comment by erickzanardo** [comment]
@RafaelBarbosatec Flame now has a built in collision detection engine, including polygon or any custom shapes. Should be quite easy to integrate it with bonfire.

**Comment by RafaelBarbosatec** [comment]
Well remembered @erickzanardo .
I'm talking to sydon to help me with this

**Comment by RafaelBarbosatec** [comment]
available in 1.0.0-rc4 version
