### ISSUE TITLE
New tile 1.5 version update. FPS issue

### ISSUE THREAD

**Issue by marvelaman** [RafaelBarbosatec/bonfire#97]
1. It throws an exception when I added new map.json via new version of Tile1.5. I just manually changed Tile version in json to 1.3.5 and it worked. 
2. I created a bigger map which causes to low fps. I guess it renders all map. I suggest to add logic which renders only visible objects in viewport. Is it implemented in dynamic rendering branch? I haven’t looked code of that branch yet

**Comment by RafaelBarbosatec** [comment]
If is possible update the Bonfire version to 1.0.0-rc2. this was corrected there
